package com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice;

import javax.xml.ws.BindingProvider;

import weblogic.wsee.jws.jaxws.owsm.SecurityPoliciesFeature;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c Development Build 12.2.1.0.0.0031
public class JournalImportServiceSoapHttpPortClient {
    public static void main(String[] args) {
        JournalImportService_Service journalImportService_Service = new JournalImportService_Service();

        // Configure security feature
        SecurityPoliciesFeature securityFeatures =
            new SecurityPoliciesFeature(new String[] { "oracle/wss_username_token_over_ssl_client_policy" });
        JournalImportService journalImportService =
            journalImportService_Service.getJournalImportServiceSoapHttpPort(securityFeatures);
        // Add your code to call the desired methods.
        ((BindingProvider)journalImportService).getRequestContext().put(BindingProvider.USERNAME_PROPERTY, "ms.tarsha");
        ((BindingProvider)journalImportService).getRequestContext().put(BindingProvider.PASSWORD_PROPERTY, "welcome123");

        try {
            journalImportService.getEntityList();
        } catch (ServiceException e) {
            e.printStackTrace();
        }


    }
}
