
package com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice;

import com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.StandardReceiptService_Service;

import innovate.tamergroup.shared.utils.FusionAppParams;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "JournalImportService",
                  targetNamespace =
                  "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/",
                  wsdlLocation =
                  "https://eenp-test.fin.em3.oraclecloud.com/finGlDesktopEntry/JournalImportService?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapps%2Ffinancials%2FgeneralLedger%2Fjournals%2FdesktopEntry%2FjournalImportService%2F%7DJournalImportService")
public class JournalImportService_Service extends Service {

    private final static URL JOURNALIMPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException JOURNALIMPORTSERVICE_EXCEPTION;
    private final static QName JOURNALIMPORTSERVICE_QNAME =
        new QName("http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/",
                  "JournalImportService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://eenp-test.fin.em3.oraclecloud.com/finGlDesktopEntry/JournalImportService?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapps%2Ffinancials%2FgeneralLedger%2Fjournals%2FdesktopEntry%2FjournalImportService%2F%7DJournalImportService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOURNALIMPORTSERVICE_WSDL_LOCATION = url;
        JOURNALIMPORTSERVICE_EXCEPTION = e;
    }

    public JournalImportService_Service() {
        super(__getWsdlLocation(), JOURNALIMPORTSERVICE_QNAME);
    }

    public JournalImportService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), JOURNALIMPORTSERVICE_QNAME, features);
    }

    public JournalImportService_Service(URL wsdlLocation) {
        super(wsdlLocation, JOURNALIMPORTSERVICE_QNAME);
    }
    
    public JournalImportService_Service(FusionAppParams params) throws MalformedURLException {
        super(new URL("https://" + params.getHostname() + ".fa." + params.getRegion() + ".oraclecloud.com/finGlDesktopEntry/JournalImportService?WSDL"), JOURNALIMPORTSERVICE_QNAME);
    }

    public JournalImportService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JOURNALIMPORTSERVICE_QNAME, features);
    }

    public JournalImportService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JournalImportService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns JournalImportService
     */
    @WebEndpoint(name = "JournalImportServiceSoapHttpPort")
    public JournalImportService getJournalImportServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/",
                                       "JournalImportServiceSoapHttpPort"), JournalImportService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JournalImportService
     */
    @WebEndpoint(name = "JournalImportServiceSoapHttpPort")
    public JournalImportService getJournalImportServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/",
                                       "JournalImportServiceSoapHttpPort"), JournalImportService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JOURNALIMPORTSERVICE_EXCEPTION != null) {
            throw JOURNALIMPORTSERVICE_EXCEPTION;
        }
        return JOURNALIMPORTSERVICE_WSDL_LOCATION;
    }

}
