
package com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice;

import java.util.List;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.oracle.xmlns.adf.svc.types.ObjAttrHints;
import com.oracle.xmlns.adf.svc.types.ServiceViewInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "JournalImportService",
            targetNamespace =
            "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/")
@XmlSeeAlso({
            com.oracle.xmlns.adf.svc.errors.ObjectFactory.class, com.oracle.xmlns.adf.svc.types.ObjectFactory.class,
            com.oracle.xmlns.apps.financials.generalledger.accounts.codecombinations.publicflex.account.ObjectFactory.class,
            com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.ObjectFactory.class,
            com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.ObjectFactory.class,
            com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class, sdo.commonj.ObjectFactory.class,
            sdo.commonj.java.ObjectFactory.class, sdo.commonj.xml.ObjectFactory.class
    })
public interface JournalImportService {


    /**
     *
     * @param interfaceRows
     * @return
     *     returns long
     * @throws ServiceException
     */
    @WebMethod(action =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/importJournals")
    @WebResult(name = "result",
               targetNamespace =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
    @RequestWrapper(localName = "importJournals",
                    targetNamespace =
                    "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                    className =
                    "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.ImportJournals")
    @ResponseWrapper(localName = "importJournalsResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                     className =
                     "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.ImportJournalsResponse")
    public long importJournals(@WebParam(name = "interfaceRows",
                                         targetNamespace =
                                         "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
                               GlInterfaceTransHeader interfaceRows) throws ServiceException;

    /**
     *
     * @param interfaceRows
     */
    @WebMethod(action =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/importJournalsAsync")
    @Oneway
    @RequestWrapper(localName = "importJournalsAsync",
                    targetNamespace =
                    "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                    className =
                    "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.ImportJournalsAsync")
    public void importJournalsAsync(@WebParam(name = "interfaceRows",
                                              targetNamespace =
                                              "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
                                    GlInterfaceTransHeader interfaceRows);

    /**
     *
     * @param viewName
     * @param localeName
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getDfltObjAttrHints")
    @WebResult(name = "result",
               targetNamespace =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints",
                    targetNamespace =
                    "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                    className =
                    "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                     className =
                     "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(@WebParam(name = "viewName",
                                                      targetNamespace =
                                                      "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
                                            String viewName,
                                            @WebParam(name = "localeName",
                                                      targetNamespace =
                                                      "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
                                            String localeName) throws ServiceException;

    /**
     *
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getServiceLastUpdateTime")
    @WebResult(name = "result",
               targetNamespace =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime",
                    targetNamespace =
                    "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                    className =
                    "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                     className =
                     "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime() throws ServiceException;

    /**
     *
     * @return
     *     returns java.util.List<com.oracle.xmlns.adf.svc.types.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getEntityList")
    @WebResult(name = "result",
               targetNamespace =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
    @RequestWrapper(localName = "getEntityList",
                    targetNamespace =
                    "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                    className =
                    "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                     className =
                     "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList() throws ServiceException;

    /**
     *
     */
    @WebMethod(action =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync",
                    targetNamespace =
                    "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                    className =
                    "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     *
     * @param viewName
     * @param localeName
     */
    @WebMethod(action =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync",
                    targetNamespace =
                    "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                    className =
                    "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(@WebParam(name = "viewName",
                                                   targetNamespace =
                                                   "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
                                         String viewName,
                                         @WebParam(name = "localeName",
                                                   targetNamespace =
                                                   "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
                                         String localeName);

    /**
     *
     */
    @WebMethod(action =
               "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync",
                    targetNamespace =
                    "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/",
                    className =
                    "com.oracle.xmlns.apps.financials.generalledger.journals.desktopentry.journalimportservice.types.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

}
