-- DROP USER ODOO_INTEGRATION;

CREATE USER ODOO_INTEGRATION
-- IDENTIFIED BY <password>
;

CREATE TABLE "ODOO_INTEGRATION"."BACKUP_VENDHQ_LINE_ITEMS" 
   (	"ROW_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(300), 
	"LINE_NUMBER" NUMBER, 
	"ITEM_NUMBER" VARCHAR2(50), 
	"ITEM_NAME" VARCHAR2(250), 
	"QUANTITY" NUMBER, 
	"LOYALTY_VALUE" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"TOTAL_TAX" NUMBER, 
	"TOTAL_DISCOUNT" NUMBER, 
	"TOTAL_LOYALTY" NUMBER, 
	"REGION" VARCHAR2(5), 
	"SALE_DATE" DATE, 
	"TAX_NAME" VARCHAR2(100), 
	 CONSTRAINT "BACKUP_VENDHQ_LINE_ITEMS_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_BVLI_ITEM_INV" ON "ODOO_INTEGRATION"."BACKUP_VENDHQ_LINE_ITEMS" ("ITEM_NUMBER", "INVOICE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_BVLI_INV_REG_DT" ON "ODOO_INTEGRATION"."BACKUP_VENDHQ_LINE_ITEMS" ("INVOICE_NUMBER", "REGION", "SALE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."BACKUP_VENDHQ_LINE_ITEMS_SABKP" 
   (	"ROW_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(300), 
	"LINE_NUMBER" NUMBER, 
	"ITEM_NUMBER" VARCHAR2(50), 
	"ITEM_NAME" VARCHAR2(250), 
	"QUANTITY" NUMBER, 
	"LOYALTY_VALUE" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"TOTAL_TAX" NUMBER, 
	"TOTAL_DISCOUNT" NUMBER, 
	"TOTAL_LOYALTY" NUMBER, 
	"REGION" VARCHAR2(5), 
	"SALE_DATE" DATE, 
	"TAX_NAME" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."BACKUP_VENDHQ_PAYMENTS" 
   (	"ROW_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(300), 
	"OUTLET_NAME" VARCHAR2(100), 
	"REGISTER_NAME" VARCHAR2(100), 
	"AMOUNT" NUMBER, 
	"CURRENCY" VARCHAR2(5), 
	"PAYMENT_TYPE" VARCHAR2(100), 
	"PAYMENT_DATE" DATE, 
	"DELETED_AT" DATE, 
	"REGION" VARCHAR2(5), 
	"SALE_DATE" DATE, 
	 CONSTRAINT "BACKUP_VENDHQ_PAYMENTS_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_BVP_INV_REG_DT" ON "ODOO_INTEGRATION"."BACKUP_VENDHQ_PAYMENTS" ("INVOICE_NUMBER", "REGION", "SALE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."BACKUP_VENDHQ_PAYMENTS_BH" 
   (	"ROW_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(300), 
	"OUTLET_NAME" VARCHAR2(100), 
	"REGISTER_NAME" VARCHAR2(100), 
	"AMOUNT" NUMBER, 
	"CURRENCY" VARCHAR2(5), 
	"PAYMENT_TYPE" VARCHAR2(100), 
	"PAYMENT_DATE" DATE, 
	"DELETED_AT" DATE, 
	"REGION" VARCHAR2(5), 
	"SALE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."BACKUP_VENDHQ_PAYMENTS_SABKP" 
   (	"ROW_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(300), 
	"OUTLET_NAME" VARCHAR2(100), 
	"REGISTER_NAME" VARCHAR2(100), 
	"AMOUNT" NUMBER, 
	"CURRENCY" VARCHAR2(5), 
	"PAYMENT_TYPE" VARCHAR2(100), 
	"PAYMENT_DATE" DATE, 
	"DELETED_AT" DATE, 
	"REGION" VARCHAR2(5), 
	"SALE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."BACKUP_VENDHQ_PROMOTIONS" 
   (	"ROW_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(15), 
	"LINE_NUMBER" NUMBER, 
	"NAME" VARCHAR2(40), 
	"AMOUNT" NUMBER, 
	"REGION" VARCHAR2(5), 
	"SALE_DATE" DATE, 
	 CONSTRAINT "BACKUP_VENDHQ_PROMOTIONS_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."BACKUP_VENDHQ_SALES" 
   (	"ROW_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(300), 
	"OUTLET_NAME" VARCHAR2(100), 
	"REGISTER_NAME" VARCHAR2(100), 
	"SALE_DATE" DATE, 
	"TOTAL_PRICE" NUMBER, 
	"TOTAL_TAX" NUMBER, 
	"TOTAL_LOYALTY" NUMBER, 
	"TOTAL_PRICE_INCL_TAX" NUMBER, 
	"VERSION" NUMBER, 
	"REGION" VARCHAR2(5), 
	"CUSTOMER_TYPE" VARCHAR2(100), 
	 CONSTRAINT "BACKUP_VENDHQ_SALES_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_BVS_REG_VER" ON "ODOO_INTEGRATION"."BACKUP_VENDHQ_SALES" ("REGION", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_BVS_OUT_REG_DT" ON "ODOO_INTEGRATION"."BACKUP_VENDHQ_SALES" ("OUTLET_NAME", "REGION", "SALE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_BVS_INV_DT" ON "ODOO_INTEGRATION"."BACKUP_VENDHQ_SALES" ("INVOICE_NUMBER", "SALE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."BACKUP_VENDHQ_SALES_BKP_BH" 
   (	"ROW_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(300), 
	"OUTLET_NAME" VARCHAR2(100), 
	"REGISTER_NAME" VARCHAR2(100), 
	"SALE_DATE" DATE, 
	"TOTAL_PRICE" NUMBER, 
	"TOTAL_TAX" NUMBER, 
	"TOTAL_LOYALTY" NUMBER, 
	"TOTAL_PRICE_INCL_TAX" NUMBER, 
	"VERSION" NUMBER, 
	"REGION" VARCHAR2(5), 
	"CUSTOMER_TYPE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."BACKUP_VENDHQ_SALES_SABKP" 
   (	"ROW_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(300), 
	"OUTLET_NAME" VARCHAR2(100), 
	"REGISTER_NAME" VARCHAR2(100), 
	"SALE_DATE" DATE, 
	"TOTAL_PRICE" NUMBER, 
	"TOTAL_TAX" NUMBER, 
	"TOTAL_LOYALTY" NUMBER, 
	"TOTAL_PRICE_INCL_TAX" NUMBER, 
	"VERSION" NUMBER, 
	"REGION" VARCHAR2(5), 
	"CUSTOMER_TYPE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."BACKUP_VNDHQ_LINE_ITEMS_BH" 
   (	"ROW_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(300), 
	"LINE_NUMBER" NUMBER, 
	"ITEM_NUMBER" VARCHAR2(50), 
	"ITEM_NAME" VARCHAR2(250), 
	"QUANTITY" NUMBER, 
	"LOYALTY_VALUE" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	"TOTAL_TAX" NUMBER, 
	"TOTAL_DISCOUNT" NUMBER, 
	"TOTAL_LOYALTY" NUMBER, 
	"REGION" VARCHAR2(5), 
	"SALE_DATE" DATE, 
	"TAX_NAME" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_APPLY_RECEIPT" 
   (	"ROW_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"MESSAGE" VARCHAR2(500), 
	"REQUEST_DATE" DATE, 
	"ACCOUNTING_DATE" DATE, 
	"APPLICATION_DATE" DATE, 
	"TXN_NUMBER" VARCHAR2(20), 
	"RECEIPT_NUMBER" VARCHAR2(50), 
	"AMOUNT_APPLIED" FLOAT(126), 
	"CURRENCY_CODE" VARCHAR2(5), 
	"REGION" VARCHAR2(5), 
	"INTEG_MODE" VARCHAR2(15), 
	"TXN_SOURCE" VARCHAR2(30), 
	 CONSTRAINT "FUSION_APPLY_RECEIPT_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FAR_REG_MODE_REQ" ON "ODOO_INTEGRATION"."FUSION_APPLY_RECEIPT" ("REGION", "INTEG_MODE", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FAR_REC_REG_REQ" ON "ODOO_INTEGRATION"."FUSION_APPLY_RECEIPT" ("RECEIPT_NUMBER", "REGION", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FAR_REQ_STS" ON "ODOO_INTEGRATION"."FUSION_APPLY_RECEIPT" ("REQUEST_ID", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_BUSINESS_UNIT_ID_MAP" 
   (	"BUSINESS_UNIT_ID" NUMBER, 
	"BUSINESS_UNIT_NAME" VARCHAR2(100), 
	"REGION" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FBUIM_REG" ON "ODOO_INTEGRATION"."FUSION_BUSINESS_UNIT_ID_MAP" ("REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_CREDENTIALS" 
   (	"ROW_ID" NUMBER, 
	"HOST_NAME" VARCHAR2(10), 
	"SERVER" VARCHAR2(3), 
	"USERNAME" VARCHAR2(30), 
	"PASSWORD" VARCHAR2(30), 
	"ACTIVE" CHAR(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FC_ACTIVE" ON "ODOO_INTEGRATION"."FUSION_CREDENTIALS" ("ACTIVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_INVOICE_HEADER" 
   (	"ROW_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"MESSAGE" VARCHAR2(500), 
	"REQUEST_DATE" DATE, 
	"BILL_TO_CUST_NAME" VARCHAR2(100), 
	"BILL_TO_LOCATION" VARCHAR2(100), 
	"BILL_TO_ACC_NUMBER" NUMBER, 
	"BUSINESS_UNIT" VARCHAR2(100), 
	"PAYMENT_TERMS_NAME" VARCHAR2(20), 
	"TXN_SOURCE" VARCHAR2(100), 
	"TXN_TYPE" VARCHAR2(100), 
	"TXN_DATE" DATE, 
	"GL_DATE" DATE, 
	"CURRENCY_CODE" VARCHAR2(5), 
	"TXN_NUMBER" NUMBER, 
	"CUSTOMER_TXN_ID" NUMBER, 
	"REGION" VARCHAR2(5), 
	 CONSTRAINT "FUSION_INVOICE_HEADER_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FIH_REG_REQ" ON "ODOO_INTEGRATION"."FUSION_INVOICE_HEADER" ("REGION", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FIH_BILL_REG_REQ" ON "ODOO_INTEGRATION"."FUSION_INVOICE_HEADER" ("BILL_TO_CUST_NAME", "REGION", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FIH_REQ_TXN" ON "ODOO_INTEGRATION"."FUSION_INVOICE_HEADER" ("REQUEST_ID", "TXN_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_INVOICE_HEADER_SA" 
   (	"ROW_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"MESSAGE" VARCHAR2(500), 
	"REQUEST_DATE" DATE, 
	"BILL_TO_CUST_NAME" VARCHAR2(100), 
	"BILL_TO_LOCATION" VARCHAR2(100), 
	"BILL_TO_ACC_NUMBER" NUMBER, 
	"BUSINESS_UNIT" VARCHAR2(100), 
	"PAYMENT_TERMS_NAME" VARCHAR2(20), 
	"TXN_SOURCE" VARCHAR2(100), 
	"TXN_TYPE" VARCHAR2(100), 
	"TXN_DATE" DATE, 
	"GL_DATE" DATE, 
	"CURRENCY_CODE" VARCHAR2(5), 
	"TXN_NUMBER" NUMBER, 
	"CUSTOMER_TXN_ID" NUMBER, 
	"REGION" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_INVOICE_LINE" 
   (	"ROW_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"MESSAGE" VARCHAR2(500), 
	"REQUEST_DATE" DATE, 
	"INVOICE_NUMBER" VARCHAR2(100), 
	"LINE_NUMBER" NUMBER, 
	"ITEM_NUMBER" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(250), 
	"UOM" VARCHAR2(10), 
	"QUANTITY" NUMBER, 
	"UNIT_SELLING_PRICE" FLOAT(126), 
	"CURRENCY_CODE" VARCHAR2(5), 
	"TAX_CODE" VARCHAR2(30), 
	"VERSION" NUMBER, 
	"SALES_ORDER" VARCHAR2(300), 
	"SALES_ORDER_LINE" NUMBER, 
	"REGION" VARCHAR2(5), 
	 CONSTRAINT "FUSION_INVOICE_LINE_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FIL_SALES" ON "ODOO_INTEGRATION"."FUSION_INVOICE_LINE" ("SALES_ORDER", "SALES_ORDER_LINE", "REGION", "VERSION", "STATUS", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FIL_REG_REQ" ON "ODOO_INTEGRATION"."FUSION_INVOICE_LINE" ("REGION", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FIL_REQ_VER" ON "ODOO_INTEGRATION"."FUSION_INVOICE_LINE" ("REQUEST_ID", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FIL_REQ_STS" ON "ODOO_INTEGRATION"."FUSION_INVOICE_LINE" ("REQUEST_ID", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_INV_TXN" 
   (	"ROW_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"MESSAGE" VARCHAR2(500), 
	"REQUEST_DATE" DATE, 
	"ORGANIZATION_NAME" VARCHAR2(50), 
	"ITEM_NUMBER" VARCHAR2(100), 
	"TXN_SOURCE_NAME" VARCHAR2(100), 
	"SUNBINVENTORY" VARCHAR2(10), 
	"TXN_UOM" VARCHAR2(10), 
	"TXN_DATE" DATE, 
	"TXN_QTY" NUMBER, 
	"REGION" VARCHAR2(5), 
	"INTEG_MODE" VARCHAR2(15), 
	 CONSTRAINT "FUSION_INV_TXN_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FIT_REG_MODE_REQ" ON "ODOO_INTEGRATION"."FUSION_INV_TXN" ("REGION", "INTEG_MODE", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FIT_SALES_ITEM" ON "ODOO_INTEGRATION"."FUSION_INV_TXN" ("TXN_SOURCE_NAME", "ITEM_NUMBER", "REGION", "TXN_DATE", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FIT_REQ_STS" ON "ODOO_INTEGRATION"."FUSION_INV_TXN" ("REQUEST_ID", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_JOURNAL_HEADER" 
   (	"ROW_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"MESSAGE" VARCHAR2(500), 
	"REQUEST_DATE" DATE, 
	"REGION" VARCHAR2(5), 
	"JE_HEADER_ID" NUMBER, 
	"LEDGER_ID" NUMBER, 
	"BATCH_NAME" VARCHAR2(100), 
	"BATCH_DESCRIPTION" VARCHAR2(250), 
	"ACCOUNTING_PERIOD_NAME" VARCHAR2(150), 
	"USER_SOURCE_NAME" VARCHAR2(150), 
	"USER_CATEGORY_NAME" VARCHAR2(100), 
	"ERROR_TO_SUSPENSE_FLAG" NUMBER, 
	"SUMMARY_FLAG" NUMBER, 
	"ACCOUNTING_DATE" DATE, 
	"IMPORT_DESCRIPTIVE_FLEX_FIELD" VARCHAR2(200), 
	"TXN_NUMBER" NUMBER, 
	"INTEG_MODE" VARCHAR2(15), 
	"CUSTOMER_TYPE" VARCHAR2(50), 
	"CASH_CREDIT" VARCHAR2(30), 
	 CONSTRAINT "FUSION_JOURNAL_HEADER_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FJH_REG_MODE_REQ" ON "ODOO_INTEGRATION"."FUSION_JOURNAL_HEADER" ("REGION", "INTEG_MODE", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FJH_TXN" ON "ODOO_INTEGRATION"."FUSION_JOURNAL_HEADER" ("TXN_NUMBER", "CUSTOMER_TYPE", "CASH_CREDIT", "REGION", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FJH_REQ_STS" ON "ODOO_INTEGRATION"."FUSION_JOURNAL_HEADER" ("REQUEST_ID", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_JOURNAL_LINE" 
   (	"ROW_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"MESSAGE" VARCHAR2(500), 
	"REQUEST_DATE" DATE, 
	"REGION" VARCHAR2(5), 
	"JE_HEADER_ID" NUMBER, 
	"JE_LINE_NUM" NUMBER, 
	"LEDGER_ID" NUMBER, 
	"GROUP_ID" NUMBER, 
	"CHART_OF_ACCOUNTS_ID" NUMBER, 
	"ENTERED_CR_AMOUNT" NUMBER, 
	"ACCOUNTED_CR" NUMBER, 
	"ENTERED_DR_AMOUNT" NUMBER, 
	"ACCOUNTED_DR" NUMBER, 
	"CURRENCY_CONVERSION_RATE" NUMBER, 
	"PERIOD_NAME" VARCHAR2(100), 
	"ACCOUNTING_PERIOD_NAME" VARCHAR2(150), 
	"USER_JE_SOURCE_NAME" VARCHAR2(150), 
	"USER_JE_CATEGORY_NAME" VARCHAR2(100), 
	"SEGMENT1" VARCHAR2(100), 
	"SEGMENT2" VARCHAR2(100), 
	"SEGMENT3" VARCHAR2(100), 
	"SEGMENT4" VARCHAR2(100), 
	"SEGMENT5" VARCHAR2(100), 
	"SEGMENT6" VARCHAR2(100), 
	"SEGMENT7" VARCHAR2(100), 
	"SEGMENT8" VARCHAR2(100), 
	"SEGMENT9" VARCHAR2(100), 
	"SEGMENT10" VARCHAR2(100), 
	"CURRENCY_CODE" VARCHAR2(100), 
	"USER_CURRENCY_CONVERSION_TYPE" VARCHAR2(100), 
	"CURRENCY_CONVERSION_TYPE" VARCHAR2(100), 
	"JE_CATEGORY_NAME" VARCHAR2(100), 
	"JE_SOURCE_NAME" VARCHAR2(100), 
	"TAX_CODE" VARCHAR2(100), 
	"RECORD_TYPE" VARCHAR2(100), 
	"ACCOUNTING_DATE" DATE, 
	"CURRENCY_CONVERSION_DATE" DATE, 
	"TRANSACTION_DATE" DATE, 
	"AVERAGE_JOURNAL_FLAG" NUMBER, 
	"SALES_ORDER" VARCHAR2(100), 
	"TXN_NUMBER" NUMBER, 
	"CUSTOMER_TYPE" VARCHAR2(100), 
	"CASH_CREDIT" VARCHAR2(30), 
	 CONSTRAINT "FUSION_JOURNAL_LINE_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_MISC_RECEIPT" 
   (	"ROW_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"MESSAGE" VARCHAR2(500), 
	"REQUEST_DATE" DATE, 
	"CURRENCY_CODE" VARCHAR2(5), 
	"GL_DATE" DATE, 
	"EXCHANGE_DATE" DATE, 
	"EXCHANGE_RATE_TYPE" VARCHAR2(20), 
	"RECEIPT_METHOD_NAME" VARCHAR2(20), 
	"RECEIPT_NUMBER" VARCHAR2(40), 
	"BANK_ACC_NUMBER" VARCHAR2(100), 
	"REC_ACTIVITY_NAME" VARCHAR2(30), 
	"AMOUNT" FLOAT(126), 
	"RECEIPT_DATE" DATE, 
	"REGION" VARCHAR2(5), 
	"INTEG_MODE" VARCHAR2(15), 
	 CONSTRAINT "FUSION_MISC_RECEIPT_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FMR_REG_MODE_REQ" ON "ODOO_INTEGRATION"."FUSION_MISC_RECEIPT" ("REGION", "INTEG_MODE", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FMR_REC_REG_REQ" ON "ODOO_INTEGRATION"."FUSION_MISC_RECEIPT" ("RECEIPT_NUMBER", "REGION", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FMR_REQ_STS" ON "ODOO_INTEGRATION"."FUSION_MISC_RECEIPT" ("REQUEST_ID", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_RECEIPT_METHOD" 
   (	"RECEIPT_METHOD_ID" NUMBER, 
	"RECEIPT_METHOD_NAME" VARCHAR2(20), 
	"RECEIPT_IS_CASH" CHAR(1), 
	"RECEIPT_BANK_CHARGE" NUMBER, 
	"RECEIPT_METHOD_TAX" NUMBER, 
	"REGION" VARCHAR2(5), 
	"ROW_ID" NUMBER, 
	 CONSTRAINT "FUSION_RECEIPT_METHOD_PK" PRIMARY KEY ("RECEIPT_METHOD_ID", "RECEIPT_METHOD_NAME", "REGION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FRM_REG_MTH" ON "ODOO_INTEGRATION"."FUSION_RECEIPT_METHOD" ("REGION", "RECEIPT_METHOD_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_SALES_METADATA" 
   (	"ROW_ID" NUMBER, 
	"BILL_TO_NAME" VARCHAR2(50), 
	"BILL_TO_ACCOUNT" NUMBER, 
	"SITE_NUMBER" VARCHAR2(20), 
	"BUSINESS_UNIT" VARCHAR2(30), 
	"TXN_SOURCE" VARCHAR2(20), 
	"TXN_TYPE" VARCHAR2(20), 
	"RATE_IS_CORPORATE" CHAR(1), 
	"REC_ACTIVITY_NAME_BANK" VARCHAR2(30), 
	"SUBINVENTORY" VARCHAR2(30), 
	"INTEGRATION_SOURCE" VARCHAR2(20), 
	"DISTRIBUTION_ACC_ID" NUMBER, 
	"REC_ACTIVITY_NAME_CASH" VARCHAR2(30), 
	"REGION" VARCHAR2(5), 
	"CUSTOMER_TYPE" VARCHAR2(30), 
	"COST_CENTER_CODE" VARCHAR2(10), 
	 CONSTRAINT "FUSION_SALES_METADATA_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FSM_LOOKUP" ON "ODOO_INTEGRATION"."FUSION_SALES_METADATA" ("SUBINVENTORY", "INTEGRATION_SOURCE", "REGION", "CUSTOMER_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FSM_BILL" ON "ODOO_INTEGRATION"."FUSION_SALES_METADATA" ("BILL_TO_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_SALES_METADATA_V18_TEMP" 
   (	"ROW_ID" NUMBER, 
	"BILL_TO_NAME" VARCHAR2(50), 
	"BILL_TO_ACCOUNT" NUMBER, 
	"SITE_NUMBER" VARCHAR2(20), 
	"BUSINESS_UNIT" VARCHAR2(30), 
	"TXN_SOURCE" VARCHAR2(20), 
	"TXN_TYPE" VARCHAR2(20), 
	"RATE_IS_CORPORATE" CHAR(1), 
	"REC_ACTIVITY_NAME_BANK" VARCHAR2(30), 
	"SUBINVENTORY" VARCHAR2(30), 
	"INTEGRATION_SOURCE" VARCHAR2(20), 
	"DISTRIBUTION_ACC_ID" NUMBER, 
	"REC_ACTIVITY_NAME_CASH" VARCHAR2(30), 
	"REGION" VARCHAR2(5), 
	"CUSTOMER_TYPE" VARCHAR2(30), 
	"COST_CENTER_CODE" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE ODOO_INTEGRATION.FUSION_SALES_METADATA_V18_TMP;

CREATE TABLE ODOO_INTEGRATION.FUSION_SALES_METADATA_V18_TMP (
	ROW_ID NUMBER,
	BILL_TO_NAME VARCHAR2(50),
	BILL_TO_ACCOUNT NUMBER,
	SITE_NUMBER VARCHAR2(20),
	BUSINESS_UNIT VARCHAR2(30),
	TXN_SOURCE VARCHAR2(20),
	TXN_TYPE VARCHAR2(20),
	RATE_IS_CORPORATE CHAR(1),
	REC_ACTIVITY_NAME_BANK VARCHAR2(30),
	SUBINVENTORY VARCHAR2(30),
	INTEGRATION_SOURCE VARCHAR2(20),
	DISTRIBUTION_ACC_ID NUMBER,
	REC_ACTIVITY_NAME_CASH VARCHAR2(30),
	REGION VARCHAR2(5),
	CUSTOMER_TYPE VARCHAR2(30),
	COST_CENTER_CODE VARCHAR2(10)
);
;

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE ODOO_INTEGRATION.FUSION_SALES_METADATA_V18_TMP1;

CREATE TABLE ODOO_INTEGRATION.FUSION_SALES_METADATA_V18_TMP1 (
	ROW_ID NUMBER,
	BILL_TO_NAME VARCHAR2(50),
	BILL_TO_ACCOUNT NUMBER,
	SITE_NUMBER VARCHAR2(20),
	BUSINESS_UNIT VARCHAR2(30),
	TXN_SOURCE VARCHAR2(20),
	TXN_TYPE VARCHAR2(20),
	RATE_IS_CORPORATE CHAR(1),
	REC_ACTIVITY_NAME_BANK VARCHAR2(30),
	SUBINVENTORY VARCHAR2(30),
	INTEGRATION_SOURCE VARCHAR2(20),
	DISTRIBUTION_ACC_ID NUMBER,
	REC_ACTIVITY_NAME_CASH VARCHAR2(30),
	REGION VARCHAR2(5),
	CUSTOMER_TYPE VARCHAR2(30),
	COST_CENTER_CODE VARCHAR2(10)
);
;

CREATE TABLE "ODOO_INTEGRATION"."FUSION_STANDARD_RECEIPT" 
   (	"ROW_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(10), 
	"MESSAGE" VARCHAR2(500), 
	"REQUEST_DATE" DATE, 
	"CURRENCY_CODE" VARCHAR2(5), 
	"RECEIPT_DATE" DATE, 
	"GL_DATE" DATE, 
	"EXCHANGE_DATE" DATE, 
	"EXCHANGE_RATE_TYPE" VARCHAR2(20), 
	"RECEIPT_METHOD_ID" NUMBER, 
	"RECEIPT_NUMBER" VARCHAR2(50), 
	"REMITTANCE_BACK_ACC_ID" VARCHAR2(20), 
	"DEPOSIT_DATE" DATE, 
	"CUSTOMER_ID" NUMBER, 
	"ORG_ID" NUMBER, 
	"AMOUNT" FLOAT(126), 
	"REGION" VARCHAR2(5), 
	"INTEG_MODE" VARCHAR2(15), 
	 CONSTRAINT "FUSION_STANDARD_RECEIPT_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FSR_REG_MODE_REQ" ON "ODOO_INTEGRATION"."FUSION_STANDARD_RECEIPT" ("REGION", "INTEG_MODE", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FSR_REC_REG_REQ" ON "ODOO_INTEGRATION"."FUSION_STANDARD_RECEIPT" ("RECEIPT_NUMBER", "REGION", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_FSR_REQ_STS" ON "ODOO_INTEGRATION"."FUSION_STANDARD_RECEIPT" ("REQUEST_ID", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."ITEM_META_BH_UPDATE" 
   (	"ID" NUMBER(38,0), 
	"NAME" VARCHAR2(128), 
	"SKU_H" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."NOTIFICATION_EMAIL_RECIPIENTS" 
   (	"ROW_ID" NUMBER, 
	"FULL_NAME" VARCHAR2(40), 
	"EMAIL_ADDRESS" VARCHAR2(40), 
	"EMAIL_MODE" VARCHAR2(4), 
	"STATUS" CHAR(1), 
	 CONSTRAINT "NOTIF_EMAIL_REC_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_NER_STATUS" ON "ODOO_INTEGRATION"."NOTIFICATION_EMAIL_RECIPIENTS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."OUTLETS_INTEGRATION_CONFIG" 
   (	"ROW_ID" NUMBER, 
	"OUTLET_NAME" VARCHAR2(200), 
	"INTEG_MODE" VARCHAR2(20), 
	"REGION" VARCHAR2(5), 
	 CONSTRAINT "OUTLETS_INTEGRATION_CONFIG_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_OIC_OUT_REG" ON "ODOO_INTEGRATION"."OUTLETS_INTEGRATION_CONFIG" ("OUTLET_NAME", "REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_OIC_MODE_REG" ON "ODOO_INTEGRATION"."OUTLETS_INTEGRATION_CONFIG" ("INTEG_MODE", "REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."SALES_INTEGRATION_STATUS" 
   (	"REGION" VARCHAR2(5), 
	"INTEG_MODE" VARCHAR2(25), 
	"STATUS" VARCHAR2(25), 
	 CONSTRAINT "SALES_INTEGRATION_STATUS_PK" PRIMARY KEY ("REGION", "INTEG_MODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."SERVICE_PROVIDER_JOURNAL_META" 
   (	"ROW_ID" NUMBER, 
	"REGION" VARCHAR2(5), 
	"LEDGER_ID" NUMBER, 
	"TAX_GROUP_ID" NUMBER, 
	"CHART_OF_ACCOUNTS_ID" NUMBER, 
	"SERVICE_PROVIDER" VARCHAR2(100), 
	"CREDIT_DEBIT" VARCHAR2(100), 
	"COST_ISSUE" VARCHAR2(100), 
	"COST_RMA" VARCHAR2(100), 
	"COMPANY" VARCHAR2(100), 
	"ACCOUNT" VARCHAR2(100), 
	"DEPARTMENT" VARCHAR2(100), 
	"PRODUCT_CATEGORY" VARCHAR2(100), 
	"INTER_COMPANY" VARCHAR2(100), 
	"FUT_USED" VARCHAR2(100), 
	"EXTRA_SEGMENT_1" VARCHAR2(100), 
	"EXTRA_SEGMENT_2" VARCHAR2(100), 
	"EXTRA_SEGMENT_3" VARCHAR2(100), 
	"JE_CATEGORY" VARCHAR2(200), 
	"JE_SOURCE" VARCHAR2(200), 
	"IS_CASH" CHAR(1), 
	"SUMMARY_FLAG" CHAR(1), 
	"FIXED_FREIGHT_CHARGE" NUMBER, 
	"BANK_CHARGE_RATE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_SPJM_LOOKUP" ON "ODOO_INTEGRATION"."SERVICE_PROVIDER_JOURNAL_META" ("REGION", "SERVICE_PROVIDER", "CREDIT_DEBIT", "IS_CASH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."TEMP_SALES_LINES" 
   (	"INVOICE_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"LINE_NUMBER" NUMBER(3,0) NOT NULL ENABLE, 
	"ITEM_NUMBER" VARCHAR2(20), 
	"ITEM_NAME" VARCHAR2(255), 
	"QUANTITY" NUMBER(10,2), 
	"TOTAL_PRICE" NUMBER(10,3), 
	"TOTAL_TAX" NUMBER(10,3), 
	"REGION" VARCHAR2(5), 
	"SALE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."TEMP_SALES_PAYMENTS" 
   (	"INVOICE_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"OUTLET_NAME" VARCHAR2(50), 
	"REGISTER_NAME" VARCHAR2(50), 
	"AMOUNT" NUMBER(10,2) NOT NULL ENABLE, 
	"CURRENCY" VARCHAR2(3) DEFAULT 'OMR', 
	"PAYMENT_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"PAYMENT_DATE" DATE, 
	"REGION" VARCHAR2(5), 
	"SALE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."VENDHQ_CREDENTIALS" 
   (	"ROW_ID" NUMBER, 
	"DOMAIN_NAME" VARCHAR2(100), 
	"PERSONAL_TOKEN" VARCHAR2(200), 
	"ACTIVE" CHAR(1), 
	"REGION" VARCHAR2(5), 
	"FUSION_ORG_CODE" VARCHAR2(10), 
	"TIMEZONE_OFFSET" NUMBER, 
	"FUSION_TAX_CODE" VARCHAR2(30), 
	"BUSINESS_START_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_VC_ACTIVE" ON "ODOO_INTEGRATION"."VENDHQ_CREDENTIALS" ("ACTIVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_VC_REGION" ON "ODOO_INTEGRATION"."VENDHQ_CREDENTIALS" ("REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."VENDHQ_DISCOUNT_ITEMS" 
   (	"ROW_ID" NUMBER, 
	"DISCOUNT_ITEM_ID" VARCHAR2(50), 
	"REGION" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_VDI_REG" ON "ODOO_INTEGRATION"."VENDHQ_DISCOUNT_ITEMS" ("REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."VENDHQ_ITEM_META" 
   (	"ROW_ID" NUMBER NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(500) NOT NULL ENABLE, 
	"ITEM_ID" VARCHAR2(50), 
	"SOURCE_ID" NUMBER, 
	"UOM_CODE" VARCHAR2(10), 
	"HANDLE" VARCHAR2(25), 
	"TYPE" VARCHAR2(50), 
	"UOM_NAME" VARCHAR2(20), 
	"ACTIVE" CHAR(1), 
	"NAME" VARCHAR2(500), 
	"DESCRIPTION" VARCHAR2(2000), 
	"SKU" VARCHAR2(30), 
	"BRAND_ID" VARCHAR2(100), 
	"TRACK_INVENTORY" CHAR(1), 
	"RETAIL_PRICE" NUMBER, 
	"TAX_ID" VARCHAR2(50), 
	"REQUEST_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE, 
	"REGION" VARCHAR2(5), 
	 CONSTRAINT "VENDHQ_ITEM_META_PK" PRIMARY KEY ("ROW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "ODOO_INTEGRATION"."VENDHQ_ITEM_META_TRIGGER" 
	before insert
	on 	VENDHQ_ITEM_META
	for each row
BEGIN
  SELECT VENDHQ_ITEM_META_ID_SEQ_GEN.NEXTVAL
  INTO   :new.ROW_ID
  FROM   dual;
END;
/
ALTER TRIGGER "ODOO_INTEGRATION"."VENDHQ_ITEM_META_TRIGGER" ENABLE;

CREATE INDEX "ODOO_INTEGRATION"."IDX_VIM_SOURCE_REGION" ON "ODOO_INTEGRATION"."VENDHQ_ITEM_META" ("SOURCE_ID", "REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IDX_VIM_REQUEST_SOURCE" ON "ODOO_INTEGRATION"."VENDHQ_ITEM_META" ("REQUEST_ID", "SOURCE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IDX_VIM_ITEM_REQUEST" ON "ODOO_INTEGRATION"."VENDHQ_ITEM_META" ("ITEM_ID", "REQUEST_ID" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IDX_VIM_REGION_LAST_UPDATE" ON "ODOO_INTEGRATION"."VENDHQ_ITEM_META" ("REGION", "LAST_UPDATE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_VIM_HDL_REG_LUD" ON "ODOO_INTEGRATION"."VENDHQ_ITEM_META" ("HANDLE", "REGION", "LAST_UPDATE_DATE" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_VIM_REQ_DT" ON "ODOO_INTEGRATION"."VENDHQ_ITEM_META" ("REQUEST_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."VENDHQ_ITEM_META_UPDATE" 
   (	"ROW_ID" NUMBER NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(500) NOT NULL ENABLE, 
	"ITEM_ID" VARCHAR2(50), 
	"SOURCE_ID" NUMBER, 
	"UOM_CODE" VARCHAR2(10), 
	"HANDLE" VARCHAR2(25), 
	"TYPE" VARCHAR2(50), 
	"UOM_NAME" VARCHAR2(20), 
	"ACTIVE" CHAR(1), 
	"NAME" VARCHAR2(500), 
	"DESCRIPTION" VARCHAR2(2000), 
	"SKU" VARCHAR2(30), 
	"BRAND_ID" VARCHAR2(100), 
	"TRACK_INVENTORY" CHAR(1), 
	"RETAIL_PRICE" NUMBER, 
	"TAX_ID" VARCHAR2(50), 
	"REQUEST_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE, 
	"REGION" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."VENDHQ_ITEM_META_V18" 
   (	"ROW_ID" NUMBER NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(500) NOT NULL ENABLE, 
	"ITEM_ID" VARCHAR2(50), 
	"SOURCE_ID" NUMBER, 
	"UOM_CODE" VARCHAR2(10), 
	"HANDLE" VARCHAR2(25), 
	"TYPE" VARCHAR2(50), 
	"UOM_NAME" VARCHAR2(20), 
	"ACTIVE" CHAR(1), 
	"NAME" VARCHAR2(500), 
	"DESCRIPTION" VARCHAR2(2000), 
	"SKU" VARCHAR2(30), 
	"BRAND_ID" VARCHAR2(100), 
	"TRACK_INVENTORY" CHAR(1), 
	"RETAIL_PRICE" NUMBER, 
	"TAX_ID" VARCHAR2(50), 
	"REQUEST_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE, 
	"REGION" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."VENDHQ_ITEM_META_V18_TEMP" 
   (	"ROW_ID" NUMBER NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(500) NOT NULL ENABLE, 
	"ITEM_ID" VARCHAR2(50), 
	"SOURCE_ID" NUMBER, 
	"UOM_CODE" VARCHAR2(10), 
	"HANDLE" VARCHAR2(25), 
	"TYPE" VARCHAR2(50), 
	"UOM_NAME" VARCHAR2(20), 
	"ACTIVE" CHAR(1), 
	"NAME" VARCHAR2(500), 
	"DESCRIPTION" VARCHAR2(2000), 
	"SKU" VARCHAR2(30), 
	"BRAND_ID" VARCHAR2(100), 
	"TRACK_INVENTORY" CHAR(1), 
	"RETAIL_PRICE" NUMBER, 
	"TAX_ID" VARCHAR2(50), 
	"REQUEST_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE, 
	"REGION" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."VENDHQ_OUTLETS" 
   (	"OUTLET_ID" VARCHAR2(100), 
	"OUTLET_NAME" VARCHAR2(250), 
	"CURRENCY" VARCHAR2(5), 
	"VERSION" NUMBER, 
	"DELETED_AT" DATE, 
	"REGION" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IDX_VO_REGION" ON "ODOO_INTEGRATION"."VENDHQ_OUTLETS" ("REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IDX_VO_OUTLET_NAME_REGION" ON "ODOO_INTEGRATION"."VENDHQ_OUTLETS" ("OUTLET_NAME", "REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IDX_VO_VERSION" ON "ODOO_INTEGRATION"."VENDHQ_OUTLETS" ("VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."VENDHQ_REGISTERS" 
   (	"REGISTER_ID" VARCHAR2(40), 
	"OUTLET_ID" VARCHAR2(40), 
	"REGISTER_NAME" VARCHAR2(30), 
	"CASH_ACCOUNT" VARCHAR2(100), 
	"CASH_ACCOUNT_ID" NUMBER, 
	"BANK_ACCOUNT" VARCHAR2(100), 
	"BANK_ACCOUNT_ID" NUMBER, 
	"VERSION" NUMBER, 
	"DELETED_AT" DATE, 
	"REGION" VARCHAR2(5), 
	"GIFT_ACCOUNT" VARCHAR2(100), 
	"GIFT_ACCOUNT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_VR_NAME_REG" ON "ODOO_INTEGRATION"."VENDHQ_REGISTERS" ("REGISTER_NAME", "REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_VR_VER" ON "ODOO_INTEGRATION"."VENDHQ_REGISTERS" ("VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."VENDHQ_SERVICE_PROVIDERS" 
   (	"ROW_ID" NUMBER, 
	"REGION" VARCHAR2(5), 
	"SERVICE_PROVIDER" VARCHAR2(100), 
	"VEDNHQ_CUSTOMER_ID" VARCHAR2(100), 
	"IS_CASH" CHAR(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IX_VSP_REG_CUST" ON "ODOO_INTEGRATION"."VENDHQ_SERVICE_PROVIDERS" ("REGION", "VEDNHQ_CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "ODOO_INTEGRATION"."VENDHQ_TAX_META" 
   (	"TAX_ID" VARCHAR2(50), 
	"TAX_NAME" VARCHAR2(50), 
	"RATE" FLOAT(126), 
	"VERSION" NUMBER, 
	"FUSION_NAME" VARCHAR2(30), 
	"REGION" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IDX_VTM_VERSION" ON "ODOO_INTEGRATION"."VENDHQ_TAX_META" ("VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE INDEX "ODOO_INTEGRATION"."IDX_VTM_REGION_TAX_NAME" ON "ODOO_INTEGRATION"."VENDHQ_TAX_META" ("REGION", "TAX_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE SEQUENCE ODOO_INTEGRATION.BACKUP_VENDHQ_LINE_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.BACKUP_VENDHQ_PAY_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.BACKUP_VENDHQ_PROMO_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.BACKUP_VENDHQ_SALES_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.FUSION_APPLY_RECEIPT_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.FUSION_CREDENTIALS_ID_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.FUSION_INVOICE_HEADER_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.FUSION_INVOICE_LINE_ID_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.FUSION_INV_TXN_ID_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.FUSION_JOURN_HDR_ID_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.FUSION_JOURN_LINE_ID_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.FUSION_MISC_RECEIPT_ID_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.FUSION_SALES_METADATA_SEQ INCREMENT BY 1 MINVALUE 562 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.FUSION_STANDARD_REC_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.FUSION_TXN_LINES_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.NOTIF_EMAIL_RECP_ID_SEQ_GEN INCREMENT BY 1 MINVALUE 3000 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.OUTLET_INTEG_CONFIG_SEQ INCREMENT BY 1 MINVALUE 900 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.REQUEST_SEQ_GEN INCREMENT BY 1 MINVALUE 23554 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.VENDHQ_DISC_ITEMS_SEQ_GEN INCREMENT BY 1 MINVALUE 21 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.VENDHQ_ITEM_META_ID_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE ODOO_INTEGRATION.VENDHQ_SALE_ONHAND_SEQ_GEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;