
package com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice;

import innovate.tamergroup.shared.utils.FusionAppParams;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InvoiceService", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/", wsdlLocation = "https://ehxk-test.fa.em2.oraclecloud.com/fscmService/RecInvoiceService?WSDL")
public class InvoiceService_Service
    extends Service
{

    private final static URL INVOICESERVICE_WSDL_LOCATION;
    private final static WebServiceException INVOICESERVICE_EXCEPTION;
    private final static QName INVOICESERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/", "InvoiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ehxk-test.fa.em2.oraclecloud.com/fscmService/RecInvoiceService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVOICESERVICE_WSDL_LOCATION = url;
        INVOICESERVICE_EXCEPTION = e;
    }

    public InvoiceService_Service() {
        super(__getWsdlLocation(), INVOICESERVICE_QNAME);
    }

    public InvoiceService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVOICESERVICE_QNAME, features);
    }

    public InvoiceService_Service(URL wsdlLocation) {
        super(wsdlLocation, INVOICESERVICE_QNAME);
    }
    
    public InvoiceService_Service(FusionAppParams params) throws MalformedURLException {
        super(new URL("https://" + params.getHostname() + ".fa.em2.oraclecloud.com/fscmService/RecInvoiceService?WSDL"), INVOICESERVICE_QNAME);
    }

    public InvoiceService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVOICESERVICE_QNAME, features);
    }

    public InvoiceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InvoiceService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InvoiceService
     */
    @WebEndpoint(name = "InvoiceServiceSoapHttpPort")
    public InvoiceService getInvoiceServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/", "InvoiceServiceSoapHttpPort"), InvoiceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InvoiceService
     */
    @WebEndpoint(name = "InvoiceServiceSoapHttpPort")
    public InvoiceService getInvoiceServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/", "InvoiceServiceSoapHttpPort"), InvoiceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVOICESERVICE_EXCEPTION!= null) {
            throw INVOICESERVICE_EXCEPTION;
        }
        return INVOICESERVICE_WSDL_LOCATION;
    }

}
