
package com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.xmlns.adf.svc.types.ObjAttrHints;
import com.oracle.xmlns.adf.svc.types.ProcessControl;
import com.oracle.xmlns.adf.svc.types.ServiceViewInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InvoiceService", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/")
@XmlSeeAlso({
    com.oracle.xmlns.adf.svc.errors.ObjectFactory.class,
    com.oracle.xmlns.adf.svc.types.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.transactions.autoinvoices.model.flex.transactioninterfacegdf.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.transactions.autoinvoices.model.flex.transactionlineinterfacegdf.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.transactions.shared.model.flex.transactiondistributiondff.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.transactions.shared.model.flex.transactionheaderdff.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.transactions.shared.model.flex.transactionheadergdf.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.transactions.shared.model.flex.transactioninterfaceheaderdff.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.transactions.shared.model.flex.transactioninterfacelinedff.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.transactions.shared.model.flex.transactionlinedff.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.transactions.shared.model.flex.transactionlinegdf.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.transactions.autoinvoices.transactioncontingencyinterfacelinedff.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.transactions.autoinvoices.transactiondistributiondff.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.transactions.autoinvoices.transactiondistributioninterfacelinedff.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.transactions.autoinvoices.transactioninterfaceheaderdff.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.transactions.autoinvoices.transactioninterfacelinktodff.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.transactions.autoinvoices.transactioninterfacereferencedff.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.transactions.autoinvoices.transactionlinedff.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.transactions.autoinvoices.transactionlineinterfacelinedff.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.transactions.autoinvoices.transactionsalescreditdff.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.transactions.autoinvoices.transactionsalescreditinterfacelinedff.ObjectFactory.class,
    com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class,
    sdo.commonj.ObjectFactory.class,
    sdo.commonj.java.ObjectFactory.class,
    sdo.commonj.xml.ObjectFactory.class
})
public interface InvoiceService {


    /**
     * 
     * @param invoiceHeaderInformation
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.InvoiceResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createSimpleInvoice")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "createSimpleInvoice", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateSimpleInvoice")
    @ResponseWrapper(localName = "createSimpleInvoiceResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateSimpleInvoiceResponse")
    public InvoiceResult createSimpleInvoice(
        @WebParam(name = "invoiceHeaderInformation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        Invoice invoiceHeaderInformation)
        throws ServiceException
    ;

    /**
     * 
     * @param invoiceHeaderInformation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createSimpleInvoiceAsync")
    @Oneway
    @RequestWrapper(localName = "createSimpleInvoiceAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateSimpleInvoiceAsync")
    public void createSimpleInvoiceAsync(
        @WebParam(name = "invoiceHeaderInformation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        Invoice invoiceHeaderInformation);

    /**
     * 
     * @param interfaceContingency
     * @param processControl
     * @param changeOperation
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.InterfaceContingency>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/processInterfaceContingency")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "processInterfaceContingency", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceContingency")
    @ResponseWrapper(localName = "processInterfaceContingencyResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceContingencyResponse")
    public List<InterfaceContingency> processInterfaceContingency(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String changeOperation,
        @WebParam(name = "interfaceContingency", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        List<InterfaceContingency> interfaceContingency,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param interfaceDistribution
     * @param processControl
     * @param changeOperation
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.InterfaceDistribution>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/processInterfaceDistribution")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "processInterfaceDistribution", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceDistribution")
    @ResponseWrapper(localName = "processInterfaceDistributionResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceDistributionResponse")
    public List<InterfaceDistribution> processInterfaceDistribution(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String changeOperation,
        @WebParam(name = "interfaceDistribution", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        List<InterfaceDistribution> interfaceDistribution,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param interfaceLine
     * @param processControl
     * @param changeOperation
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.InterfaceLine>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/processInterfaceLine")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "processInterfaceLine", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceLine")
    @ResponseWrapper(localName = "processInterfaceLineResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceLineResponse")
    public List<InterfaceLine> processInterfaceLine(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String changeOperation,
        @WebParam(name = "interfaceLine", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        List<InterfaceLine> interfaceLine,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param interfaceSalesCredit
     * @param processControl
     * @param changeOperation
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.InterfaceSalesCredit>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/processInterfaceSalesCredit")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "processInterfaceSalesCredit", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceSalesCredit")
    @ResponseWrapper(localName = "processInterfaceSalesCreditResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceSalesCreditResponse")
    public List<InterfaceSalesCredit> processInterfaceSalesCredit(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String changeOperation,
        @WebParam(name = "interfaceSalesCredit", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        List<InterfaceSalesCredit> interfaceSalesCredit,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param interfaceDistribution
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/processInterfaceDistributionAsync")
    @Oneway
    @RequestWrapper(localName = "processInterfaceDistributionAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceDistributionAsync")
    public void processInterfaceDistributionAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String changeOperation,
        @WebParam(name = "interfaceDistribution", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        List<InterfaceDistribution> interfaceDistribution,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param interfaceSalesCredit
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/processInterfaceSalesCreditAsync")
    @Oneway
    @RequestWrapper(localName = "processInterfaceSalesCreditAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceSalesCreditAsync")
    public void processInterfaceSalesCreditAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String changeOperation,
        @WebParam(name = "interfaceSalesCredit", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        List<InterfaceSalesCredit> interfaceSalesCredit,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param interfaceLine
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/processInterfaceLineAsync")
    @Oneway
    @RequestWrapper(localName = "processInterfaceLineAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceLineAsync")
    public void processInterfaceLineAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String changeOperation,
        @WebParam(name = "interfaceLine", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        List<InterfaceLine> interfaceLine,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param interfaceContingency
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/processInterfaceContingencyAsync")
    @Oneway
    @RequestWrapper(localName = "processInterfaceContingencyAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessInterfaceContingencyAsync")
    public void processInterfaceContingencyAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String changeOperation,
        @WebParam(name = "interfaceContingency", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        List<InterfaceContingency> interfaceContingency,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param interfaceContingency
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.InterfaceContingency
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createInterfaceContingency")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "createInterfaceContingency", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceContingency")
    @ResponseWrapper(localName = "createInterfaceContingencyResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceContingencyResponse")
    public InterfaceContingency createInterfaceContingency(
        @WebParam(name = "interfaceContingency", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        InterfaceContingency interfaceContingency)
        throws ServiceException
    ;

    /**
     * 
     * @param interfaceDistribution
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.InterfaceDistribution
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createInterfaceDistribution")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "createInterfaceDistribution", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceDistribution")
    @ResponseWrapper(localName = "createInterfaceDistributionResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceDistributionResponse")
    public InterfaceDistribution createInterfaceDistribution(
        @WebParam(name = "interfaceDistribution", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        InterfaceDistribution interfaceDistribution)
        throws ServiceException
    ;

    /**
     * 
     * @param interfaceLine
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.InterfaceLine
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createInterfaceLine")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "createInterfaceLine", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceLine")
    @ResponseWrapper(localName = "createInterfaceLineResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceLineResponse")
    public InterfaceLine createInterfaceLine(
        @WebParam(name = "interfaceLine", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        InterfaceLine interfaceLine)
        throws ServiceException
    ;

    /**
     * 
     * @param interfaceSalesCredit
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.InterfaceSalesCredit
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createInterfaceSalesCredit")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "createInterfaceSalesCredit", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceSalesCredit")
    @ResponseWrapper(localName = "createInterfaceSalesCreditResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceSalesCreditResponse")
    public InterfaceSalesCredit createInterfaceSalesCredit(
        @WebParam(name = "interfaceSalesCredit", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        InterfaceSalesCredit interfaceSalesCredit)
        throws ServiceException
    ;

    /**
     * 
     * @param interfaceSalesCredit
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createInterfaceSalesCreditAsync")
    @Oneway
    @RequestWrapper(localName = "createInterfaceSalesCreditAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceSalesCreditAsync")
    public void createInterfaceSalesCreditAsync(
        @WebParam(name = "interfaceSalesCredit", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        InterfaceSalesCredit interfaceSalesCredit);

    /**
     * 
     * @param interfaceLine
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createInterfaceLineAsync")
    @Oneway
    @RequestWrapper(localName = "createInterfaceLineAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceLineAsync")
    public void createInterfaceLineAsync(
        @WebParam(name = "interfaceLine", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        InterfaceLine interfaceLine);

    /**
     * 
     * @param interfaceContingency
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createInterfaceContingencyAsync")
    @Oneway
    @RequestWrapper(localName = "createInterfaceContingencyAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceContingencyAsync")
    public void createInterfaceContingencyAsync(
        @WebParam(name = "interfaceContingency", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        InterfaceContingency interfaceContingency);

    /**
     * 
     * @param interfaceDistribution
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createInterfaceDistributionAsync")
    @Oneway
    @RequestWrapper(localName = "createInterfaceDistributionAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateInterfaceDistributionAsync")
    public void createInterfaceDistributionAsync(
        @WebParam(name = "interfaceDistribution", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        InterfaceDistribution interfaceDistribution);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.oracle.xmlns.adf.svc.types.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

    /**
     * 
     * @param updateCCToken
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.UpdateCCTokenResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createUpdateCCToken")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "createUpdateCCToken", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateUpdateCCToken")
    @ResponseWrapper(localName = "createUpdateCCTokenResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateUpdateCCTokenResponse")
    public UpdateCCTokenResult createUpdateCCToken(
        @WebParam(name = "updateCCToken", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        UpdateCCToken updateCCToken)
        throws ServiceException
    ;

    /**
     * 
     * @param updateCCToken
     * @param processControl
     * @param changeOperation
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.UpdateCCTokenResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/processUpdateCCToken")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
    @RequestWrapper(localName = "processUpdateCCToken", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessUpdateCCToken")
    @ResponseWrapper(localName = "processUpdateCCTokenResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessUpdateCCTokenResponse")
    public UpdateCCTokenResult processUpdateCCToken(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String changeOperation,
        @WebParam(name = "updateCCToken", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        List<UpdateCCToken> updateCCToken,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param updateCCToken
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/createUpdateCCTokenAsync")
    @Oneway
    @RequestWrapper(localName = "createUpdateCCTokenAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.CreateUpdateCCTokenAsync")
    public void createUpdateCCTokenAsync(
        @WebParam(name = "updateCCToken", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        UpdateCCToken updateCCToken);

    /**
     * 
     * @param updateCCToken
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/processUpdateCCTokenAsync")
    @Oneway
    @RequestWrapper(localName = "processUpdateCCTokenAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/", className = "com.oracle.xmlns.apps.financials.receivables.transactions.invoices.invoiceservice.types.ProcessUpdateCCTokenAsync")
    public void processUpdateCCTokenAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        String changeOperation,
        @WebParam(name = "updateCCToken", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        List<UpdateCCToken> updateCCToken,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/transactions/invoices/invoiceService/types/")
        ProcessControl processControl);

}
