#!/bin/bash
# 01-create-user.sh - Create ODOO_INTEGRATION user and grant privileges

echo "Creating ODOO_INTEGRATION user..."

sqlplus -s sys/${ORACLE_PWD}@localhost:1521/${ORACLE_SID} as sysdba <<EOF
-- Create user
CREATE USER ODOO_INTEGRATION IDENTIFIED BY "${DB_PASSWORD:-Oracle123}";

-- Grant privileges
GRANT CONNECT, RESOURCE TO ODOO_INTEGRATION;
GRANT CREATE SESSION TO ODOO_INTEGRATION;
GRANT CREATE TABLE TO ODOO_INTEGRATION;
GRANT CREATE VIEW TO ODOO_INTEGRATION;
GRANT CREATE SEQUENCE TO ODOO_INTEGRATION;
GRANT CREATE TRIGGER TO ODOO_INTEGRATION;
GRANT CREATE PROCEDURE TO ODOO_INTEGRATION;
GRANT UNLIMITED TABLESPACE TO ODOO_INTEGRATION;

-- Grant additional privileges for application
GRANT SELECT ANY TABLE TO ODOO_INTEGRATION;
GRANT INSERT ANY TABLE TO ODOO_INTEGRATION;
GRANT UPDATE ANY TABLE TO ODOO_INTEGRATION;
GRANT DELETE ANY TABLE TO ODOO_INTEGRATION;

EXIT;
EOF

echo "ODOO_INTEGRATION user created successfully"
