-- 02-create-schema.sql
-- Oracle Database Schema for ODOO_INTEGRATION
-- Simplified version compatible with Oracle Express Edition

CONNECT ODOO_INTEGRATION/${DB_PASSWORD:-Oracle123}@${ORACLE_SID};

-- Create sequences first
CREATE SEQUENCE BACKUP_VENDHQ_LINE_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE BACKUP_VENDHQ_PAY_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE BACKUP_VENDHQ_PROMO_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE BACKUP_VENDHQ_SALES_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE FUSION_APPLY_RECEIPT_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE FUSION_CREDENTIALS_ID_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE FUSION_INVOICE_HEADER_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE FUSION_INVOICE_LINE_ID_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE FUSION_INV_TXN_ID_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE FUSION_JOURN_HDR_ID_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE FUSION_JOURN_LINE_ID_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE FUSION_MISC_RECEIPT_ID_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE FUSION_SALES_METADATA_SEQ START WITH 562 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE FUSION_STANDARD_REC_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE FUSION_TXN_LINES_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE NOTIF_EMAIL_RECP_ID_SEQ_GEN START WITH 3000 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE OUTLET_INTEG_CONFIG_SEQ START WITH 900 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE REQUEST_SEQ_GEN START WITH 23554 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE VENDHQ_DISC_ITEMS_SEQ_GEN START WITH 21 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE VENDHQ_ITEM_META_ID_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE VENDHQ_SALE_ONHAND_SEQ_GEN START WITH 1 INCREMENT BY 1 NOCYCLE;

-- BACKUP_VENDHQ_LINE_ITEMS table
CREATE TABLE BACKUP_VENDHQ_LINE_ITEMS (
    ROW_ID NUMBER PRIMARY KEY,
    INVOICE_NUMBER VARCHAR2(300),
    LINE_NUMBER NUMBER,
    ITEM_NUMBER VARCHAR2(50),
    ITEM_NAME VARCHAR2(250),
    QUANTITY NUMBER,
    LOYALTY_VALUE NUMBER,
    TOTAL_PRICE NUMBER,
    TOTAL_TAX NUMBER,
    TOTAL_DISCOUNT NUMBER,
    TOTAL_LOYALTY NUMBER,
    REGION VARCHAR2(5),
    SALE_DATE DATE,
    TAX_NAME VARCHAR2(100)
);

CREATE INDEX IX_BVLI_ITEM_INV ON BACKUP_VENDHQ_LINE_ITEMS(ITEM_NUMBER, INVOICE_NUMBER);
CREATE INDEX IX_BVLI_INV_REG_DT ON BACKUP_VENDHQ_LINE_ITEMS(INVOICE_NUMBER, REGION, SALE_DATE);

-- BACKUP_VENDHQ_PAYMENTS table
CREATE TABLE BACKUP_VENDHQ_PAYMENTS (
    ROW_ID NUMBER PRIMARY KEY,
    INVOICE_NUMBER VARCHAR2(300),
    OUTLET_NAME VARCHAR2(100),
    REGISTER_NAME VARCHAR2(100),
    AMOUNT NUMBER,
    CURRENCY VARCHAR2(5),
    PAYMENT_TYPE VARCHAR2(100),
    PAYMENT_DATE DATE,
    DELETED_AT DATE,
    REGION VARCHAR2(5),
    SALE_DATE DATE
);

CREATE INDEX IX_BVP_INV_REG_DT ON BACKUP_VENDHQ_PAYMENTS(INVOICE_NUMBER, REGION, SALE_DATE);

-- BACKUP_VENDHQ_PROMOTIONS table
CREATE TABLE BACKUP_VENDHQ_PROMOTIONS (
    ROW_ID NUMBER PRIMARY KEY,
    INVOICE_NUMBER VARCHAR2(15),
    LINE_NUMBER NUMBER,
    NAME VARCHAR2(40),
    AMOUNT NUMBER,
    REGION VARCHAR2(5),
    SALE_DATE DATE
);

-- BACKUP_VENDHQ_SALES table
CREATE TABLE BACKUP_VENDHQ_SALES (
    ROW_ID NUMBER PRIMARY KEY,
    INVOICE_NUMBER VARCHAR2(300),
    OUTLET_NAME VARCHAR2(100),
    REGISTER_NAME VARCHAR2(100),
    SALE_DATE DATE,
    TOTAL_PRICE NUMBER,
    TOTAL_TAX NUMBER,
    TOTAL_LOYALTY NUMBER,
    TOTAL_PRICE_INCL_TAX NUMBER,
    VERSION NUMBER,
    REGION VARCHAR2(5),
    CUSTOMER_TYPE VARCHAR2(100)
);

CREATE INDEX IX_BVS_REG_VER ON BACKUP_VENDHQ_SALES(REGION, VERSION);
CREATE INDEX IX_BVS_OUT_REG_DT ON BACKUP_VENDHQ_SALES(OUTLET_NAME, REGION, SALE_DATE);
CREATE INDEX IX_BVS_INV_DT ON BACKUP_VENDHQ_SALES(INVOICE_NUMBER, SALE_DATE);

-- FUSION_APPLY_RECEIPT table
CREATE TABLE FUSION_APPLY_RECEIPT (
    ROW_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER,
    STATUS VARCHAR2(20),
    MESSAGE VARCHAR2(500),
    REQUEST_DATE DATE,
    ACCOUNTING_DATE DATE,
    APPLICATION_DATE DATE,
    TXN_NUMBER VARCHAR2(20),
    RECEIPT_NUMBER VARCHAR2(50),
    AMOUNT_APPLIED FLOAT,
    CURRENCY_CODE VARCHAR2(5),
    REGION VARCHAR2(5),
    INTEG_MODE VARCHAR2(15),
    TXN_SOURCE VARCHAR2(30)
);

CREATE INDEX IX_FAR_REG_MODE_REQ ON FUSION_APPLY_RECEIPT(REGION, INTEG_MODE, REQUEST_ID DESC);
CREATE INDEX IX_FAR_REC_REG_REQ ON FUSION_APPLY_RECEIPT(RECEIPT_NUMBER, REGION, REQUEST_ID DESC);
CREATE INDEX IX_FAR_REQ_STS ON FUSION_APPLY_RECEIPT(REQUEST_ID, STATUS);

-- FUSION_BUSINESS_UNIT_ID_MAP table
CREATE TABLE FUSION_BUSINESS_UNIT_ID_MAP (
    BUSINESS_UNIT_ID NUMBER,
    BUSINESS_UNIT_NAME VARCHAR2(100),
    REGION VARCHAR2(5)
);

CREATE INDEX IX_FBUIM_REG ON FUSION_BUSINESS_UNIT_ID_MAP(REGION);

-- FUSION_CREDENTIALS table
CREATE TABLE FUSION_CREDENTIALS (
    ROW_ID NUMBER PRIMARY KEY,
    HOST_NAME VARCHAR2(10),
    SERVER VARCHAR2(3),
    USERNAME VARCHAR2(30),
    PASSWORD VARCHAR2(30),
    ACTIVE CHAR(1)
);

CREATE INDEX IX_FC_ACTIVE ON FUSION_CREDENTIALS(ACTIVE);

-- FUSION_INVOICE_HEADER table
CREATE TABLE FUSION_INVOICE_HEADER (
    ROW_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER,
    STATUS VARCHAR2(20),
    MESSAGE VARCHAR2(500),
    REQUEST_DATE DATE,
    BILL_TO_CUST_NAME VARCHAR2(100),
    BILL_TO_LOCATION VARCHAR2(100),
    BILL_TO_ACC_NUMBER NUMBER,
    BUSINESS_UNIT VARCHAR2(100),
    PAYMENT_TERMS_NAME VARCHAR2(20),
    TXN_SOURCE VARCHAR2(100),
    TXN_TYPE VARCHAR2(100),
    TXN_DATE DATE,
    GL_DATE DATE,
    CURRENCY_CODE VARCHAR2(5),
    TXN_NUMBER NUMBER,
    CUSTOMER_TXN_ID NUMBER,
    REGION VARCHAR2(5)
);

CREATE INDEX IX_FIH_REG_REQ ON FUSION_INVOICE_HEADER(REGION, REQUEST_ID DESC);
CREATE INDEX IX_FIH_BILL_REG_REQ ON FUSION_INVOICE_HEADER(BILL_TO_CUST_NAME, REGION, REQUEST_ID DESC);
CREATE INDEX IX_FIH_REQ_TXN ON FUSION_INVOICE_HEADER(REQUEST_ID, TXN_DATE);

-- FUSION_INVOICE_LINE table
CREATE TABLE FUSION_INVOICE_LINE (
    ROW_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER,
    STATUS VARCHAR2(20),
    MESSAGE VARCHAR2(500),
    REQUEST_DATE DATE,
    INVOICE_NUMBER VARCHAR2(100),
    LINE_NUMBER NUMBER,
    ITEM_NUMBER VARCHAR2(100),
    DESCRIPTION VARCHAR2(250),
    UOM VARCHAR2(10),
    QUANTITY NUMBER,
    UNIT_SELLING_PRICE FLOAT,
    CURRENCY_CODE VARCHAR2(5),
    TAX_CODE VARCHAR2(30),
    VERSION NUMBER,
    SALES_ORDER VARCHAR2(300),
    SALES_ORDER_LINE NUMBER,
    REGION VARCHAR2(5)
);

CREATE INDEX IX_FIL_SALES ON FUSION_INVOICE_LINE(SALES_ORDER, SALES_ORDER_LINE, REGION, VERSION, STATUS, REQUEST_ID DESC);
CREATE INDEX IX_FIL_REG_REQ ON FUSION_INVOICE_LINE(REGION, REQUEST_ID DESC);
CREATE INDEX IX_FIL_REQ_VER ON FUSION_INVOICE_LINE(REQUEST_ID, VERSION);
CREATE INDEX IX_FIL_REQ_STS ON FUSION_INVOICE_LINE(REQUEST_ID, STATUS);

-- FUSION_INV_TXN table
CREATE TABLE FUSION_INV_TXN (
    ROW_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER,
    STATUS VARCHAR2(20),
    MESSAGE VARCHAR2(500),
    REQUEST_DATE DATE,
    ORGANIZATION_NAME VARCHAR2(50),
    ITEM_NUMBER VARCHAR2(100),
    TXN_SOURCE_NAME VARCHAR2(100),
    SUNBINVENTORY VARCHAR2(10),
    TXN_UOM VARCHAR2(10),
    TXN_DATE DATE,
    TXN_QTY NUMBER,
    REGION VARCHAR2(5),
    INTEG_MODE VARCHAR2(15)
);

CREATE INDEX IX_FIT_REG_MODE_REQ ON FUSION_INV_TXN(REGION, INTEG_MODE, REQUEST_ID DESC);
CREATE INDEX IX_FIT_SALES_ITEM ON FUSION_INV_TXN(TXN_SOURCE_NAME, ITEM_NUMBER, REGION, TXN_DATE, REQUEST_ID DESC);
CREATE INDEX IX_FIT_REQ_STS ON FUSION_INV_TXN(REQUEST_ID, STATUS);

-- FUSION_JOURNAL_HEADER table
CREATE TABLE FUSION_JOURNAL_HEADER (
    ROW_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER,
    STATUS VARCHAR2(20),
    MESSAGE VARCHAR2(500),
    REQUEST_DATE DATE,
    REGION VARCHAR2(5),
    JE_HEADER_ID NUMBER,
    LEDGER_ID NUMBER,
    BATCH_NAME VARCHAR2(100),
    BATCH_DESCRIPTION VARCHAR2(250),
    ACCOUNTING_PERIOD_NAME VARCHAR2(150),
    USER_SOURCE_NAME VARCHAR2(150),
    USER_CATEGORY_NAME VARCHAR2(100),
    ERROR_TO_SUSPENSE_FLAG NUMBER,
    SUMMARY_FLAG NUMBER,
    ACCOUNTING_DATE DATE,
    IMPORT_DESCRIPTIVE_FLEX_FIELD VARCHAR2(200),
    TXN_NUMBER NUMBER,
    INTEG_MODE VARCHAR2(15),
    CUSTOMER_TYPE VARCHAR2(50),
    CASH_CREDIT VARCHAR2(30)
);

CREATE INDEX IX_FJH_REG_MODE_REQ ON FUSION_JOURNAL_HEADER(REGION, INTEG_MODE, REQUEST_ID DESC);
CREATE INDEX IX_FJH_TXN ON FUSION_JOURNAL_HEADER(TXN_NUMBER, CUSTOMER_TYPE, CASH_CREDIT, REGION, REQUEST_ID DESC);
CREATE INDEX IX_FJH_REQ_STS ON FUSION_JOURNAL_HEADER(REQUEST_ID, STATUS);

-- FUSION_JOURNAL_LINE table
CREATE TABLE FUSION_JOURNAL_LINE (
    ROW_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER,
    STATUS VARCHAR2(20),
    MESSAGE VARCHAR2(500),
    REQUEST_DATE DATE,
    REGION VARCHAR2(5),
    JE_HEADER_ID NUMBER,
    JE_LINE_NUM NUMBER,
    LEDGER_ID NUMBER,
    GROUP_ID NUMBER,
    CHART_OF_ACCOUNTS_ID NUMBER,
    ENTERED_CR_AMOUNT NUMBER,
    ACCOUNTED_CR NUMBER,
    ENTERED_DR_AMOUNT NUMBER,
    ACCOUNTED_DR NUMBER,
    CURRENCY_CONVERSION_RATE NUMBER,
    PERIOD_NAME VARCHAR2(100),
    ACCOUNTING_PERIOD_NAME VARCHAR2(150),
    USER_JE_SOURCE_NAME VARCHAR2(150),
    USER_JE_CATEGORY_NAME VARCHAR2(100),
    SEGMENT1 VARCHAR2(100),
    SEGMENT2 VARCHAR2(100),
    SEGMENT3 VARCHAR2(100),
    SEGMENT4 VARCHAR2(100),
    SEGMENT5 VARCHAR2(100),
    SEGMENT6 VARCHAR2(100),
    SEGMENT7 VARCHAR2(100),
    SEGMENT8 VARCHAR2(100),
    SEGMENT9 VARCHAR2(100),
    SEGMENT10 VARCHAR2(100),
    CURRENCY_CODE VARCHAR2(100),
    USER_CURRENCY_CONVERSION_TYPE VARCHAR2(100),
    CURRENCY_CONVERSION_TYPE VARCHAR2(100),
    JE_CATEGORY_NAME VARCHAR2(100),
    JE_SOURCE_NAME VARCHAR2(100),
    TAX_CODE VARCHAR2(100),
    RECORD_TYPE VARCHAR2(100),
    ACCOUNTING_DATE DATE,
    CURRENCY_CONVERSION_DATE DATE,
    TRANSACTION_DATE DATE,
    AVERAGE_JOURNAL_FLAG NUMBER,
    SALES_ORDER VARCHAR2(100),
    TXN_NUMBER NUMBER,
    CUSTOMER_TYPE VARCHAR2(100),
    CASH_CREDIT VARCHAR2(30)
);

-- FUSION_MISC_RECEIPT table
CREATE TABLE FUSION_MISC_RECEIPT (
    ROW_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER,
    STATUS VARCHAR2(20),
    MESSAGE VARCHAR2(500),
    REQUEST_DATE DATE,
    CURRENCY_CODE VARCHAR2(5),
    GL_DATE DATE,
    EXCHANGE_DATE DATE,
    EXCHANGE_RATE_TYPE VARCHAR2(20),
    RECEIPT_METHOD_NAME VARCHAR2(20),
    RECEIPT_NUMBER VARCHAR2(40),
    BANK_ACC_NUMBER VARCHAR2(100),
    REC_ACTIVITY_NAME VARCHAR2(30),
    AMOUNT FLOAT,
    RECEIPT_DATE DATE,
    REGION VARCHAR2(5),
    INTEG_MODE VARCHAR2(15)
);

CREATE INDEX IX_FMR_REG_MODE_REQ ON FUSION_MISC_RECEIPT(REGION, INTEG_MODE, REQUEST_ID DESC);
CREATE INDEX IX_FMR_REC_REG_REQ ON FUSION_MISC_RECEIPT(RECEIPT_NUMBER, REGION, REQUEST_ID DESC);
CREATE INDEX IX_FMR_REQ_STS ON FUSION_MISC_RECEIPT(REQUEST_ID, STATUS);

-- FUSION_RECEIPT_METHOD table
CREATE TABLE FUSION_RECEIPT_METHOD (
    RECEIPT_METHOD_ID NUMBER,
    RECEIPT_METHOD_NAME VARCHAR2(20),
    RECEIPT_IS_CASH CHAR(1),
    RECEIPT_BANK_CHARGE NUMBER,
    RECEIPT_METHOD_TAX NUMBER,
    REGION VARCHAR2(5),
    ROW_ID NUMBER,
    CONSTRAINT FUSION_RECEIPT_METHOD_PK PRIMARY KEY (RECEIPT_METHOD_ID, RECEIPT_METHOD_NAME, REGION)
);

CREATE INDEX IX_FRM_REG_MTH ON FUSION_RECEIPT_METHOD(REGION, RECEIPT_METHOD_NAME);

-- FUSION_SALES_METADATA table
CREATE TABLE FUSION_SALES_METADATA (
    ROW_ID NUMBER PRIMARY KEY,
    BILL_TO_NAME VARCHAR2(50),
    BILL_TO_ACCOUNT NUMBER,
    SITE_NUMBER VARCHAR2(20),
    BUSINESS_UNIT VARCHAR2(30),
    TXN_SOURCE VARCHAR2(20),
    TXN_TYPE VARCHAR2(20),
    RATE_IS_CORPORATE CHAR(1),
    REC_ACTIVITY_NAME_BANK VARCHAR2(30),
    SUBINVENTORY VARCHAR2(30),
    INTEGRATION_SOURCE VARCHAR2(20),
    DISTRIBUTION_ACC_ID NUMBER,
    REC_ACTIVITY_NAME_CASH VARCHAR2(30),
    REGION VARCHAR2(5),
    CUSTOMER_TYPE VARCHAR2(30),
    COST_CENTER_CODE VARCHAR2(10)
);

CREATE INDEX IX_FSM_LOOKUP ON FUSION_SALES_METADATA(SUBINVENTORY, INTEGRATION_SOURCE, REGION, CUSTOMER_TYPE);
CREATE INDEX IX_FSM_BILL ON FUSION_SALES_METADATA(BILL_TO_NAME);

-- FUSION_STANDARD_RECEIPT table
CREATE TABLE FUSION_STANDARD_RECEIPT (
    ROW_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER,
    STATUS VARCHAR2(10),
    MESSAGE VARCHAR2(500),
    REQUEST_DATE DATE,
    CURRENCY_CODE VARCHAR2(5),
    RECEIPT_DATE DATE,
    GL_DATE DATE,
    EXCHANGE_DATE DATE,
    EXCHANGE_RATE_TYPE VARCHAR2(20),
    RECEIPT_METHOD_ID NUMBER,
    RECEIPT_NUMBER VARCHAR2(50),
    REMITTANCE_BACK_ACC_ID VARCHAR2(20),
    DEPOSIT_DATE DATE,
    CUSTOMER_ID NUMBER,
    ORG_ID NUMBER,
    AMOUNT FLOAT,
    REGION VARCHAR2(5),
    INTEG_MODE VARCHAR2(15)
);

CREATE INDEX IX_FSR_REG_MODE_REQ ON FUSION_STANDARD_RECEIPT(REGION, INTEG_MODE, REQUEST_ID DESC);
CREATE INDEX IX_FSR_REC_REG_REQ ON FUSION_STANDARD_RECEIPT(RECEIPT_NUMBER, REGION, REQUEST_ID DESC);
CREATE INDEX IX_FSR_REQ_STS ON FUSION_STANDARD_RECEIPT(REQUEST_ID, STATUS);

-- NOTIFICATION_EMAIL_RECIPIENTS table
CREATE TABLE NOTIFICATION_EMAIL_RECIPIENTS (
    ROW_ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(40),
    EMAIL_ADDRESS VARCHAR2(40),
    EMAIL_MODE VARCHAR2(4),
    STATUS CHAR(1)
);

CREATE INDEX IX_NER_STATUS ON NOTIFICATION_EMAIL_RECIPIENTS(STATUS);

-- OUTLETS_INTEGRATION_CONFIG table
CREATE TABLE OUTLETS_INTEGRATION_CONFIG (
    ROW_ID NUMBER PRIMARY KEY,
    OUTLET_NAME VARCHAR2(200),
    INTEG_MODE VARCHAR2(20),
    REGION VARCHAR2(5)
);

CREATE INDEX IX_OIC_OUT_REG ON OUTLETS_INTEGRATION_CONFIG(OUTLET_NAME, REGION);
CREATE INDEX IX_OIC_MODE_REG ON OUTLETS_INTEGRATION_CONFIG(INTEG_MODE, REGION);

-- SALES_INTEGRATION_STATUS table
CREATE TABLE SALES_INTEGRATION_STATUS (
    REGION VARCHAR2(5),
    INTEG_MODE VARCHAR2(25),
    STATUS VARCHAR2(25),
    CONSTRAINT SALES_INTEGRATION_STATUS_PK PRIMARY KEY (REGION, INTEG_MODE)
);

-- SERVICE_PROVIDER_JOURNAL_META table
CREATE TABLE SERVICE_PROVIDER_JOURNAL_META (
    ROW_ID NUMBER,
    REGION VARCHAR2(5),
    LEDGER_ID NUMBER,
    TAX_GROUP_ID NUMBER,
    CHART_OF_ACCOUNTS_ID NUMBER,
    SERVICE_PROVIDER VARCHAR2(100),
    CREDIT_DEBIT VARCHAR2(100),
    COST_ISSUE VARCHAR2(100),
    COST_RMA VARCHAR2(100),
    COMPANY VARCHAR2(100),
    ACCOUNT VARCHAR2(100),
    DEPARTMENT VARCHAR2(100),
    PRODUCT_CATEGORY VARCHAR2(100),
    INTER_COMPANY VARCHAR2(100),
    FUT_USED VARCHAR2(100),
    EXTRA_SEGMENT_1 VARCHAR2(100),
    EXTRA_SEGMENT_2 VARCHAR2(100),
    EXTRA_SEGMENT_3 VARCHAR2(100),
    JE_CATEGORY VARCHAR2(200),
    JE_SOURCE VARCHAR2(200),
    IS_CASH CHAR(1),
    SUMMARY_FLAG CHAR(1),
    FIXED_FREIGHT_CHARGE NUMBER,
    BANK_CHARGE_RATE NUMBER
);

CREATE INDEX IX_SPJM_LOOKUP ON SERVICE_PROVIDER_JOURNAL_META(REGION, SERVICE_PROVIDER, CREDIT_DEBIT, IS_CASH);

-- TEMP_SALES_LINES table
CREATE TABLE TEMP_SALES_LINES (
    INVOICE_NUMBER VARCHAR2(50) NOT NULL,
    LINE_NUMBER NUMBER(3,0) NOT NULL,
    ITEM_NUMBER VARCHAR2(20),
    ITEM_NAME VARCHAR2(255),
    QUANTITY NUMBER(10,2),
    TOTAL_PRICE NUMBER(10,3),
    TOTAL_TAX NUMBER(10,3),
    REGION VARCHAR2(5),
    SALE_DATE DATE
);

-- TEMP_SALES_PAYMENTS table
CREATE TABLE TEMP_SALES_PAYMENTS (
    INVOICE_NUMBER VARCHAR2(50) NOT NULL,
    OUTLET_NAME VARCHAR2(50),
    REGISTER_NAME VARCHAR2(50),
    AMOUNT NUMBER(10,2) NOT NULL,
    CURRENCY VARCHAR2(3) DEFAULT 'OMR',
    PAYMENT_TYPE VARCHAR2(50) NOT NULL,
    PAYMENT_DATE DATE,
    REGION VARCHAR2(5),
    SALE_DATE DATE
);

-- VENDHQ_CREDENTIALS table
CREATE TABLE VENDHQ_CREDENTIALS (
    ROW_ID NUMBER PRIMARY KEY,
    DOMAIN_NAME VARCHAR2(100),
    PERSONAL_TOKEN VARCHAR2(200),
    ACTIVE CHAR(1),
    REGION VARCHAR2(5),
    FUSION_ORG_CODE VARCHAR2(10),
    TIMEZONE_OFFSET NUMBER,
    FUSION_TAX_CODE VARCHAR2(30),
    BUSINESS_START_DATE DATE
);

CREATE INDEX IX_VC_ACTIVE ON VENDHQ_CREDENTIALS(ACTIVE);
CREATE INDEX IX_VC_REGION ON VENDHQ_CREDENTIALS(REGION);

-- VENDHQ_DISCOUNT_ITEMS table
CREATE TABLE VENDHQ_DISCOUNT_ITEMS (
    ROW_ID NUMBER PRIMARY KEY,
    DISCOUNT_ITEM_ID VARCHAR2(50),
    REGION VARCHAR2(5)
);

CREATE INDEX IX_VDI_REG ON VENDHQ_DISCOUNT_ITEMS(REGION);

-- VENDHQ_ITEM_META table
CREATE TABLE VENDHQ_ITEM_META (
    ROW_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER NOT NULL,
    STATUS VARCHAR2(10) NOT NULL,
    MESSAGE VARCHAR2(500) NOT NULL,
    ITEM_ID VARCHAR2(50),
    SOURCE_ID NUMBER,
    UOM_CODE VARCHAR2(10),
    HANDLE VARCHAR2(25),
    TYPE VARCHAR2(50),
    UOM_NAME VARCHAR2(20),
    ACTIVE CHAR(1),
    NAME VARCHAR2(500),
    DESCRIPTION VARCHAR2(2000),
    SKU VARCHAR2(30),
    BRAND_ID VARCHAR2(100),
    TRACK_INVENTORY CHAR(1),
    RETAIL_PRICE NUMBER,
    TAX_ID VARCHAR2(50),
    REQUEST_DATE DATE NOT NULL,
    LAST_UPDATE_DATE DATE,
    REGION VARCHAR2(5)
);

CREATE INDEX IDX_VIM_SOURCE_REGION ON VENDHQ_ITEM_META(SOURCE_ID, REGION);
CREATE INDEX IDX_VIM_REQUEST_SOURCE ON VENDHQ_ITEM_META(REQUEST_ID, SOURCE_ID);
CREATE INDEX IDX_VIM_ITEM_REQUEST ON VENDHQ_ITEM_META(ITEM_ID, REQUEST_ID DESC);
CREATE INDEX IDX_VIM_REGION_LAST_UPDATE ON VENDHQ_ITEM_META(REGION, LAST_UPDATE_DATE);
CREATE INDEX IX_VIM_HDL_REG_LUD ON VENDHQ_ITEM_META(HANDLE, REGION, LAST_UPDATE_DATE DESC);
CREATE INDEX IX_VIM_REQ_DT ON VENDHQ_ITEM_META(REQUEST_DATE);

-- Create trigger for VENDHQ_ITEM_META
CREATE OR REPLACE TRIGGER VENDHQ_ITEM_META_TRIGGER
BEFORE INSERT ON VENDHQ_ITEM_META
FOR EACH ROW
BEGIN
  IF :new.ROW_ID IS NULL THEN
    SELECT VENDHQ_ITEM_META_ID_SEQ_GEN.NEXTVAL INTO :new.ROW_ID FROM dual;
  END IF;
END;
/

-- VENDHQ_OUTLETS table
CREATE TABLE VENDHQ_OUTLETS (
    OUTLET_ID VARCHAR2(100),
    OUTLET_NAME VARCHAR2(250),
    CURRENCY VARCHAR2(5),
    VERSION NUMBER,
    DELETED_AT DATE,
    REGION VARCHAR2(5)
);

CREATE INDEX IDX_VO_REGION ON VENDHQ_OUTLETS(REGION);
CREATE INDEX IDX_VO_OUTLET_NAME_REGION ON VENDHQ_OUTLETS(OUTLET_NAME, REGION);
CREATE INDEX IDX_VO_VERSION ON VENDHQ_OUTLETS(VERSION);

-- VENDHQ_REGISTERS table
CREATE TABLE VENDHQ_REGISTERS (
    REGISTER_ID VARCHAR2(40),
    OUTLET_ID VARCHAR2(40),
    REGISTER_NAME VARCHAR2(30),
    CASH_ACCOUNT VARCHAR2(100),
    CASH_ACCOUNT_ID NUMBER,
    BANK_ACCOUNT VARCHAR2(100),
    BANK_ACCOUNT_ID NUMBER,
    VERSION NUMBER,
    DELETED_AT DATE,
    REGION VARCHAR2(5),
    GIFT_ACCOUNT VARCHAR2(100),
    GIFT_ACCOUNT_ID NUMBER
);

CREATE INDEX IX_VR_NAME_REG ON VENDHQ_REGISTERS(REGISTER_NAME, REGION);
CREATE INDEX IX_VR_VER ON VENDHQ_REGISTERS(VERSION);

-- VENDHQ_SERVICE_PROVIDERS table
CREATE TABLE VENDHQ_SERVICE_PROVIDERS (
    ROW_ID NUMBER PRIMARY KEY,
    REGION VARCHAR2(5),
    SERVICE_PROVIDER VARCHAR2(100),
    VEDNHQ_CUSTOMER_ID VARCHAR2(100),
    IS_CASH CHAR(100)
);

CREATE INDEX IX_VSP_REG_CUST ON VENDHQ_SERVICE_PROVIDERS(REGION, VEDNHQ_CUSTOMER_ID);

-- VENDHQ_TAX_META table
CREATE TABLE VENDHQ_TAX_META (
    TAX_ID VARCHAR2(50),
    TAX_NAME VARCHAR2(50),
    RATE FLOAT,
    VERSION NUMBER,
    FUSION_NAME VARCHAR2(30),
    REGION VARCHAR2(5)
);

CREATE INDEX IDX_VTM_VERSION ON VENDHQ_TAX_META(VERSION);
CREATE INDEX IDX_VTM_REGION_TAX_NAME ON VENDHQ_TAX_META(REGION, TAX_NAME);

COMMIT;

-- Display success message
SELECT 'Database schema created successfully!' AS STATUS FROM DUAL;
