
package com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.xmlns.adf.svc.types.ObjAttrHints;
import com.oracle.xmlns.adf.svc.types.ServiceViewInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerProfileService", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/")
@XmlSeeAlso({
    com.oracle.xmlns.adf.svc.errors.ObjectFactory.class,
    com.oracle.xmlns.adf.svc.types.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.customersetup.customerprofiles.model.flex.customerprofiledff.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.customersetup.customerprofiles.model.flex.customerprofilegdf.ObjectFactory.class,
    com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class,
    sdo.commonj.ObjectFactory.class,
    sdo.commonj.java.ObjectFactory.class,
    sdo.commonj.xml.ObjectFactory.class
})
public interface CustomerProfileService {


    /**
     * 
     * @param customerProfile
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.CustomerProfileResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/createCustomerProfile")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
    @RequestWrapper(localName = "createCustomerProfile", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.CreateCustomerProfile")
    @ResponseWrapper(localName = "createCustomerProfileResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.CreateCustomerProfileResponse")
    public CustomerProfileResult createCustomerProfile(
        @WebParam(name = "customerProfile", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
        CustomerProfile customerProfile)
        throws ServiceException
    ;

    /**
     * 
     * @param customerProfile
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.CustomerProfileResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/updateCustomerProfile")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
    @RequestWrapper(localName = "updateCustomerProfile", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.UpdateCustomerProfile")
    @ResponseWrapper(localName = "updateCustomerProfileResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.UpdateCustomerProfileResponse")
    public CustomerProfileResult updateCustomerProfile(
        @WebParam(name = "customerProfile", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
        CustomerProfile customerProfile)
        throws ServiceException
    ;

    /**
     * 
     * @param customerProfile
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/createCustomerProfileAsync")
    @Oneway
    @RequestWrapper(localName = "createCustomerProfileAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.CreateCustomerProfileAsync")
    public void createCustomerProfileAsync(
        @WebParam(name = "customerProfile", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
        CustomerProfile customerProfile);

    /**
     * 
     * @param customerProfile
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/updateCustomerProfileAsync")
    @Oneway
    @RequestWrapper(localName = "updateCustomerProfileAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.UpdateCustomerProfileAsync")
    public void updateCustomerProfileAsync(
        @WebParam(name = "customerProfile", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
        CustomerProfile customerProfile);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.oracle.xmlns.adf.svc.types.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

    /**
     * 
     * @param customerProfile
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.CustomerProfileResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/getActiveCustomerProfile")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
    @RequestWrapper(localName = "getActiveCustomerProfile", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetActiveCustomerProfile")
    @ResponseWrapper(localName = "getActiveCustomerProfileResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetActiveCustomerProfileResponse")
    public CustomerProfileResult getActiveCustomerProfile(
        @WebParam(name = "customerProfile", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
        CustomerProfile customerProfile)
        throws ServiceException
    ;

    /**
     * 
     * @param customerProfile
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/getActiveCustomerProfileAsync")
    @Oneway
    @RequestWrapper(localName = "getActiveCustomerProfileAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/", className = "com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice.types.GetActiveCustomerProfileAsync")
    public void getActiveCustomerProfileAsync(
        @WebParam(name = "customerProfile", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/types/")
        CustomerProfile customerProfile);

}
