
package com.oracle.xmlns.apps.financials.receivables.customers.customerprofileservice;

import innovate.tamergroup.shared.utils.FusionAppParams;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerProfileService", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/", wsdlLocation = "https://ehxk-test.fa.em2.oraclecloud.com/fscmService/ReceivablesCustomerProfileService?WSDL")
public class CustomerProfileService_Service
    extends Service
{

    private final static URL CUSTOMERPROFILESERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERPROFILESERVICE_EXCEPTION;
    private final static QName CUSTOMERPROFILESERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/", "CustomerProfileService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ehxk-test.fa.em2.oraclecloud.com/fscmService/ReceivablesCustomerProfileService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERPROFILESERVICE_WSDL_LOCATION = url;
        CUSTOMERPROFILESERVICE_EXCEPTION = e;
    }

    public CustomerProfileService_Service() {
        super(__getWsdlLocation(), CUSTOMERPROFILESERVICE_QNAME);
    }

    public CustomerProfileService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERPROFILESERVICE_QNAME, features);
    }

    public CustomerProfileService_Service(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERPROFILESERVICE_QNAME);
    }
    
    public CustomerProfileService_Service(FusionAppParams params) throws MalformedURLException {
        super(new URL("https://" + params.getHostname() + ".fa." + params.getRegion() + ".oraclecloud.com/fscmService/ReceivablesCustomerProfileService?WSDL"), CUSTOMERPROFILESERVICE_QNAME);
    }

    public CustomerProfileService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERPROFILESERVICE_QNAME, features);
    }

    public CustomerProfileService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerProfileService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerProfileService
     */
    @WebEndpoint(name = "CustomerProfileServiceSoapHttpPort")
    public CustomerProfileService getCustomerProfileServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/", "CustomerProfileServiceSoapHttpPort"), CustomerProfileService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerProfileService
     */
    @WebEndpoint(name = "CustomerProfileServiceSoapHttpPort")
    public CustomerProfileService getCustomerProfileServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/receivables/customers/customerProfileService/", "CustomerProfileServiceSoapHttpPort"), CustomerProfileService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERPROFILESERVICE_EXCEPTION!= null) {
            throw CUSTOMERPROFILESERVICE_EXCEPTION;
        }
        return CUSTOMERPROFILESERVICE_WSDL_LOCATION;
    }

}
