
package com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.xmlns.adf.svc.types.FindControl;
import com.oracle.xmlns.adf.svc.types.FindCriteria;
import com.oracle.xmlns.adf.svc.types.ObjAttrHints;
import com.oracle.xmlns.adf.svc.types.ProcessControl;
import com.oracle.xmlns.adf.svc.types.ServiceViewInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StandardReceiptService", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/")
@XmlSeeAlso({
    com.oracle.xmlns.adf.svc.errors.ObjectFactory.class,
    com.oracle.xmlns.adf.svc.types.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.receipts.shared.model.flex.standardreceiptdff.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.receipts.shared.model.flex.standardreceiptgdf.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.receipts.shared.standardreceiptservice.commonservice.activityapplicationdff.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.receipts.shared.standardreceiptservice.commonservice.activityapplicationgdf.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.receipts.shared.standardreceiptservice.commonservice.applyonaccountdff.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.receipts.shared.standardreceiptservice.commonservice.applyonaccountgdf.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.financials.receivables.receipts.shared.standardreceiptservice.commonservice.applyreceiptdff.ObjectFactory.class,
    com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class,
    sdo.commonj.ObjectFactory.class,
    sdo.commonj.java.ObjectFactory.class,
    sdo.commonj.xml.ObjectFactory.class
})
public interface StandardReceiptService {


    /**
     * 
     * @param standardReceipt
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.StandardReceiptResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createStandardReceipt")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "createStandardReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateStandardReceipt")
    @ResponseWrapper(localName = "createStandardReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateStandardReceiptResponse")
    public StandardReceiptResult createStandardReceipt(
        @WebParam(name = "standardReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        StandardReceipt standardReceipt)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.StandardReceiptResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/findStandardReceipt")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "findStandardReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.FindStandardReceipt")
    @ResponseWrapper(localName = "findStandardReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.FindStandardReceiptResponse")
    public StandardReceiptResult findStandardReceipt(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param standardReceipt
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createStandardReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "createStandardReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateStandardReceiptAsync")
    public void createStandardReceiptAsync(
        @WebParam(name = "standardReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        StandardReceipt standardReceipt);

    /**
     * 
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/findStandardReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "findStandardReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.FindStandardReceiptAsync")
    public void findStandardReceiptAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        FindControl findControl);

    /**
     * 
     * @param reverseReceipt
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ReverseReceiptResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createReverseReceipt")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "createReverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateReverseReceipt")
    @ResponseWrapper(localName = "createReverseReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateReverseReceiptResponse")
    public ReverseReceiptResult createReverseReceipt(
        @WebParam(name = "reverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ReverseReceipt reverseReceipt)
        throws ServiceException
    ;

    /**
     * 
     * @param unapplyReceipt
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyReceiptResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createUnapplyReceipt")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "createUnapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyReceipt")
    @ResponseWrapper(localName = "createUnapplyReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyReceiptResponse")
    public UnapplyReceiptResult createUnapplyReceipt(
        @WebParam(name = "unapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        UnapplyReceipt unapplyReceipt)
        throws ServiceException
    ;

    /**
     * 
     * @param reverseReceipt
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createReverseReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "createReverseReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateReverseReceiptAsync")
    public void createReverseReceiptAsync(
        @WebParam(name = "reverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ReverseReceipt reverseReceipt);

    /**
     * 
     * @param unapplyReceipt
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createUnapplyReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "createUnapplyReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyReceiptAsync")
    public void createUnapplyReceiptAsync(
        @WebParam(name = "unapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        UnapplyReceipt unapplyReceipt);

    /**
     * 
     * @param reverseReceipt
     * @param processControl
     * @param changeOperation
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ReverseReceiptResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processReverseReceipt")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "processReverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessReverseReceipt")
    @ResponseWrapper(localName = "processReverseReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessReverseReceiptResponse")
    public ReverseReceiptResult processReverseReceipt(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "reverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<ReverseReceipt> reverseReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param unapplyReceipt
     * @param processControl
     * @param changeOperation
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyReceiptResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processUnapplyReceipt")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "processUnapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyReceipt")
    @ResponseWrapper(localName = "processUnapplyReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyReceiptResponse")
    public UnapplyReceiptResult processUnapplyReceipt(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "unapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<UnapplyReceipt> unapplyReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param reverseReceipt
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processReverseReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "processReverseReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessReverseReceiptAsync")
    public void processReverseReceiptAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "reverseReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<ReverseReceipt> reverseReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param unapplyReceipt
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processUnapplyReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "processUnapplyReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyReceiptAsync")
    public void processUnapplyReceiptAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "unapplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<UnapplyReceipt> unapplyReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param unapplyOnAccount
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyOnAccountResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createUnapplyOnAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "createUnapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyOnAccount")
    @ResponseWrapper(localName = "createUnapplyOnAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyOnAccountResponse")
    public UnapplyOnAccountResult createUnapplyOnAccount(
        @WebParam(name = "unapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        UnapplyOnAccount unapplyOnAccount)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param unapplyOnAccount
     * @param changeOperation
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.UnapplyOnAccountResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processUnapplyOnAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "processUnapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyOnAccount")
    @ResponseWrapper(localName = "processUnapplyOnAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyOnAccountResponse")
    public UnapplyOnAccountResult processUnapplyOnAccount(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "unapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<UnapplyOnAccount> unapplyOnAccount,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param unapplyOnAccount
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createUnapplyOnAccountAsync")
    @Oneway
    @RequestWrapper(localName = "createUnapplyOnAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateUnapplyOnAccountAsync")
    public void createUnapplyOnAccountAsync(
        @WebParam(name = "unapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        UnapplyOnAccount unapplyOnAccount);

    /**
     * 
     * @param processControl
     * @param unapplyOnAccount
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processUnapplyOnAccountAsync")
    @Oneway
    @RequestWrapper(localName = "processUnapplyOnAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessUnapplyOnAccountAsync")
    public void processUnapplyOnAccountAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "unapplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<UnapplyOnAccount> unapplyOnAccount,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param applyOnAccount
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyOnAccountResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createApplyOnAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "createApplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyOnAccount")
    @ResponseWrapper(localName = "createApplyOnAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyOnAccountResponse")
    public ApplyOnAccountResult createApplyOnAccount(
        @WebParam(name = "applyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ApplyOnAccount applyOnAccount)
        throws ServiceException
    ;

    /**
     * 
     * @param applyOnAccount
     * @param processControl
     * @param changeOperation
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyOnAccountResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processApplyOnAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "processApplyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyOnAccount")
    @ResponseWrapper(localName = "processApplyOnAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyOnAccountResponse")
    public ApplyOnAccountResult processApplyOnAccount(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "applyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<ApplyOnAccount> applyOnAccount,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param applyOnAccount
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createApplyOnAccountAsync")
    @Oneway
    @RequestWrapper(localName = "createApplyOnAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyOnAccountAsync")
    public void createApplyOnAccountAsync(
        @WebParam(name = "applyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ApplyOnAccount applyOnAccount);

    /**
     * 
     * @param applyOnAccount
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processApplyOnAccountAsync")
    @Oneway
    @RequestWrapper(localName = "processApplyOnAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyOnAccountAsync")
    public void processApplyOnAccountAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "applyOnAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<ApplyOnAccount> applyOnAccount,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param activityApplication
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityApplicationResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createActivityApplication")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "createActivityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityApplication")
    @ResponseWrapper(localName = "createActivityApplicationResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityApplicationResponse")
    public ActivityApplicationResult createActivityApplication(
        @WebParam(name = "activityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ActivityApplication activityApplication)
        throws ServiceException
    ;

    /**
     * 
     * @param activityApplication
     * @param processControl
     * @param changeOperation
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityApplicationResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processActivityApplication")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "processActivityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityApplication")
    @ResponseWrapper(localName = "processActivityApplicationResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityApplicationResponse")
    public ActivityApplicationResult processActivityApplication(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "activityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<ActivityApplication> activityApplication,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param activityUnapplication
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityUnapplicationResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createActivityUnapplication")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "createActivityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityUnapplication")
    @ResponseWrapper(localName = "createActivityUnapplicationResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityUnapplicationResponse")
    public ActivityUnapplicationResult createActivityUnapplication(
        @WebParam(name = "activityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ActivityUnapplication activityUnapplication)
        throws ServiceException
    ;

    /**
     * 
     * @param activityUnapplication
     * @param processControl
     * @param changeOperation
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ActivityUnapplicationResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processActivityUnapplication")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "processActivityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityUnapplication")
    @ResponseWrapper(localName = "processActivityUnapplicationResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityUnapplicationResponse")
    public ActivityUnapplicationResult processActivityUnapplication(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "activityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<ActivityUnapplication> activityUnapplication,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param activityApplication
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processActivityApplicationAsync")
    @Oneway
    @RequestWrapper(localName = "processActivityApplicationAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityApplicationAsync")
    public void processActivityApplicationAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "activityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<ActivityApplication> activityApplication,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param activityUnapplication
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processActivityUnapplicationAsync")
    @Oneway
    @RequestWrapper(localName = "processActivityUnapplicationAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessActivityUnapplicationAsync")
    public void processActivityUnapplicationAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "activityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<ActivityUnapplication> activityUnapplication,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param activityApplication
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createActivityApplicationAsync")
    @Oneway
    @RequestWrapper(localName = "createActivityApplicationAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityApplicationAsync")
    public void createActivityApplicationAsync(
        @WebParam(name = "activityApplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ActivityApplication activityApplication);

    /**
     * 
     * @param activityUnapplication
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createActivityUnapplicationAsync")
    @Oneway
    @RequestWrapper(localName = "createActivityUnapplicationAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateActivityUnapplicationAsync")
    public void createActivityUnapplicationAsync(
        @WebParam(name = "activityUnapplication", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ActivityUnapplication activityUnapplication);

    /**
     * 
     * @param applyReceipt
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyReceiptResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createApplyReceipt")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "createApplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyReceipt")
    @ResponseWrapper(localName = "createApplyReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyReceiptResponse")
    public ApplyReceiptResult createApplyReceipt(
        @WebParam(name = "applyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ApplyReceipt applyReceipt)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param applyReceipt
     * @param changeOperation
     * @return
     *     returns com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.ApplyReceiptResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processApplyReceipt")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "processApplyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyReceipt")
    @ResponseWrapper(localName = "processApplyReceiptResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyReceiptResponse")
    public ApplyReceiptResult processApplyReceipt(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "applyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<ApplyReceipt> applyReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param applyReceipt
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/processApplyReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "processApplyReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.ProcessApplyReceiptAsync")
    public void processApplyReceiptAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String changeOperation,
        @WebParam(name = "applyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        List<ApplyReceipt> applyReceipt,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param applyReceipt
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/createApplyReceiptAsync")
    @Oneway
    @RequestWrapper(localName = "createApplyReceiptAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.CreateApplyReceiptAsync")
    public void createApplyReceiptAsync(
        @WebParam(name = "applyReceipt", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        ApplyReceipt applyReceipt);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.oracle.xmlns.adf.svc.types.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/types/", className = "com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice.types.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

}
