
package com.oracle.xmlns.apps.financials.receivables.receipts.shared.standardreceiptservice.commonservice;

import innovate.tamergroup.shared.utils.FusionAppParams;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StandardReceiptService", targetNamespace = "http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/", wsdlLocation = "https://ehxk-test.fa.em2.oraclecloud.com/fscmService/StandardReceiptService?WSDL")
public class StandardReceiptService_Service
    extends Service
{

    private final static URL STANDARDRECEIPTSERVICE_WSDL_LOCATION;
    private final static WebServiceException STANDARDRECEIPTSERVICE_EXCEPTION;
    private final static QName STANDARDRECEIPTSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/", "StandardReceiptService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ehxk-test.fa.em2.oraclecloud.com/fscmService/StandardReceiptService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STANDARDRECEIPTSERVICE_WSDL_LOCATION = url;
        STANDARDRECEIPTSERVICE_EXCEPTION = e;
    }

    public StandardReceiptService_Service() {
        super(__getWsdlLocation(), STANDARDRECEIPTSERVICE_QNAME);
    }

    public StandardReceiptService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), STANDARDRECEIPTSERVICE_QNAME, features);
    }

    public StandardReceiptService_Service(URL wsdlLocation) {
        super(wsdlLocation, STANDARDRECEIPTSERVICE_QNAME);
    }
    
    public StandardReceiptService_Service(FusionAppParams params) throws MalformedURLException {
        super(new URL("https://" + params.getHostname() + ".fa." + params.getRegion() + ".oraclecloud.com/fscmService/StandardReceiptService?WSDL"), STANDARDRECEIPTSERVICE_QNAME);
    }

    public StandardReceiptService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STANDARDRECEIPTSERVICE_QNAME, features);
    }

    public StandardReceiptService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StandardReceiptService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StandardReceiptService
     */
    @WebEndpoint(name = "StandardReceiptServiceSoapHttpPort")
    public StandardReceiptService getStandardReceiptServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/", "StandardReceiptServiceSoapHttpPort"), StandardReceiptService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StandardReceiptService
     */
    @WebEndpoint(name = "StandardReceiptServiceSoapHttpPort")
    public StandardReceiptService getStandardReceiptServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/receivables/receipts/shared/standardReceiptService/commonService/", "StandardReceiptServiceSoapHttpPort"), StandardReceiptService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STANDARDRECEIPTSERVICE_EXCEPTION!= null) {
            throw STANDARDRECEIPTSERVICE_EXCEPTION;
        }
        return STANDARDRECEIPTSERVICE_WSDL_LOCATION;
    }

}
