package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 18 12:18:13 AST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StatusListImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StatusListImpl() {
    }
}

