package model;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 05 11:51:14 AST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VendhqSaleItemsOnhandViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_VENDHQSALEITEMSONHAND = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        RowId1,
        OrgCode,
        Subinventory,
        ItemNumber,
        UomCode,
        OnhandQty,
        ReservedQty,
        ReceivingQty,
        LastUpdateDate,
        SaleQty,
        BalanceQty;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ROWID1 = AttributesEnum.RowId1.index();
    public static final int ORGCODE = AttributesEnum.OrgCode.index();
    public static final int SUBINVENTORY = AttributesEnum.Subinventory.index();
    public static final int ITEMNUMBER = AttributesEnum.ItemNumber.index();
    public static final int UOMCODE = AttributesEnum.UomCode.index();
    public static final int ONHANDQTY = AttributesEnum.OnhandQty.index();
    public static final int RESERVEDQTY = AttributesEnum.ReservedQty.index();
    public static final int RECEIVINGQTY = AttributesEnum.ReceivingQty.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int SALEQTY = AttributesEnum.SaleQty.index();
    public static final int BALANCEQTY = AttributesEnum.BalanceQty.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VendhqSaleItemsOnhandViewRowImpl() {
    }

    /**
     * Gets VendhqSaleItemsOnhand entity object.
     * @return the VendhqSaleItemsOnhand
     */
    public EntityImpl getVendhqSaleItemsOnhand() {
        return (EntityImpl) getEntity(ENTITY_VENDHQSALEITEMSONHAND);
    }

    /**
     * Gets the attribute value for ROW_ID using the alias name RowId1.
     * @return the ROW_ID
     */
    public BigDecimal getRowId1() {
        return (BigDecimal) getAttributeInternal(ROWID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ROW_ID using the alias name RowId1.
     * @param value value to set the ROW_ID
     */
    public void setRowId1(BigDecimal value) {
        setAttributeInternal(ROWID1, value);
    }

    /**
     * Gets the attribute value for ORG_CODE using the alias name OrgCode.
     * @return the ORG_CODE
     */
    public String getOrgCode() {
        return (String) getAttributeInternal(ORGCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_CODE using the alias name OrgCode.
     * @param value value to set the ORG_CODE
     */
    public void setOrgCode(String value) {
        setAttributeInternal(ORGCODE, value);
    }

    /**
     * Gets the attribute value for SUBINVENTORY using the alias name Subinventory.
     * @return the SUBINVENTORY
     */
    public String getSubinventory() {
        return (String) getAttributeInternal(SUBINVENTORY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBINVENTORY using the alias name Subinventory.
     * @param value value to set the SUBINVENTORY
     */
    public void setSubinventory(String value) {
        setAttributeInternal(SUBINVENTORY, value);
    }

    /**
     * Gets the attribute value for ITEM_NUMBER using the alias name ItemNumber.
     * @return the ITEM_NUMBER
     */
    public String getItemNumber() {
        return (String) getAttributeInternal(ITEMNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_NUMBER using the alias name ItemNumber.
     * @param value value to set the ITEM_NUMBER
     */
    public void setItemNumber(String value) {
        setAttributeInternal(ITEMNUMBER, value);
    }

    /**
     * Gets the attribute value for UOM_CODE using the alias name UomCode.
     * @return the UOM_CODE
     */
    public String getUomCode() {
        return (String) getAttributeInternal(UOMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM_CODE using the alias name UomCode.
     * @param value value to set the UOM_CODE
     */
    public void setUomCode(String value) {
        setAttributeInternal(UOMCODE, value);
    }

    /**
     * Gets the attribute value for ONHAND_QTY using the alias name OnhandQty.
     * @return the ONHAND_QTY
     */
    public BigDecimal getOnhandQty() {
        return (BigDecimal) getAttributeInternal(ONHANDQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for ONHAND_QTY using the alias name OnhandQty.
     * @param value value to set the ONHAND_QTY
     */
    public void setOnhandQty(BigDecimal value) {
        setAttributeInternal(ONHANDQTY, value);
    }

    /**
     * Gets the attribute value for RESERVED_QTY using the alias name ReservedQty.
     * @return the RESERVED_QTY
     */
    public BigDecimal getReservedQty() {
        return (BigDecimal) getAttributeInternal(RESERVEDQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for RESERVED_QTY using the alias name ReservedQty.
     * @param value value to set the RESERVED_QTY
     */
    public void setReservedQty(BigDecimal value) {
        setAttributeInternal(RESERVEDQTY, value);
    }

    /**
     * Gets the attribute value for RECEIVING_QTY using the alias name ReceivingQty.
     * @return the RECEIVING_QTY
     */
    public BigDecimal getReceivingQty() {
        return (BigDecimal) getAttributeInternal(RECEIVINGQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVING_QTY using the alias name ReceivingQty.
     * @param value value to set the RECEIVING_QTY
     */
    public void setReceivingQty(BigDecimal value) {
        setAttributeInternal(RECEIVINGQTY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for SALE_QTY using the alias name SaleQty.
     * @return the SALE_QTY
     */
    public BigDecimal getSaleQty() {
        return (BigDecimal) getAttributeInternal(SALEQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for SALE_QTY using the alias name SaleQty.
     * @param value value to set the SALE_QTY
     */
    public void setSaleQty(BigDecimal value) {
        setAttributeInternal(SALEQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BalanceQty.
     * @return the BalanceQty
     */
    public BigDecimal getBalanceQty() {
        if (getSaleQty() == null) return BigDecimal.valueOf(0L);
        else return getOnhandQty().subtract(getSaleQty());
    }
}

