'use strict';

/**
 * odooToVendhqMapper.js
 *
 * Maps Odoo API data to VendHQ backup table structure following the patterns
 * established in the Java middleware mapping classes.
 *
 * This module provides field-by-field transformation from:
 *   - Odoo sale.order        → BACKUP_VENDHQ_SALES
 *   - Odoo sale.order.line   → BACKUP_VENDHQ_LINE_ITEMS
 *   - Odoo account.payment   → BACKUP_VENDHQ_PAYMENTS
 *
 * The resulting mapped data is compatible with the Oracle push operations:
 *   1. AR Invoice (from SALES + LINE_ITEMS)
 *   2. Standard Receipt (from PAYMENTS - main payments)
 *   3. Misc Receipt (from PAYMENTS - rounding, tips, etc.)
 *   4. Apply Receipt (links receipts to invoices)
 *   5. Journal Entry (service provider charges)
 *
 * References:
 *   - database.sql: ODOO_INTEGRATION schema tables
 *   - FusionInvoiceMapping.java: Invoice header/line mapping logic
 *   - FusionStdReceiptMapping.java: Standard receipt mapping
 *   - FusionMiscReceiptMapping.java: Misc receipt mapping
 *   - FusionApplyReceiptMapping.java: Apply receipt logic
 *   - FusionJournalEntryMapping.java: Journal entry mapping
 */

// ─────────────────────────────────────────────────────────────────────────────
// 1. Sale Order → BACKUP_VENDHQ_SALES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Map Odoo sale.order to BACKUP_VENDHQ_SALES table structure.
 *
 * BACKUP_VENDHQ_SALES columns:
 *   - ROW_ID: NUMBER (Primary Key, auto-generated)
 *   - INVOICE_NUMBER: VARCHAR2(300) - Odoo order name/reference
 *   - OUTLET_NAME: VARCHAR2(100) - Store/warehouse name
 *   - REGISTER_NAME: VARCHAR2(100) - POS register name
 *   - SALE_DATE: DATE - Order date
 *   - TOTAL_PRICE: NUMBER - Subtotal (excluding tax)
 *   - TOTAL_TAX: NUMBER - Total tax amount
 *   - TOTAL_LOYALTY: NUMBER - Loyalty/discount amount
 *   - TOTAL_PRICE_INCL_TAX: NUMBER - Grand total (including tax)
 *   - VERSION: NUMBER - Version number (always 0 for Odoo)
 *   - REGION: VARCHAR2(5) - Country/region code
 *   - CUSTOMER_TYPE: VARCHAR2(100) - Customer type (e.g., NORMAL, HUNGERSTATION, TALABAT)
 *
 * @param {object} odooSale - Odoo sale.order object from API
 * @param {object} options - Additional mapping options
 * @param {string} options.region - Region code (e.g., 'AE', 'SA', 'KW')
 * @param {string} options.outletName - Store/outlet name override
 * @param {string} options.registerName - Register name override
 * @param {string} options.customerType - Customer type (default: 'NORMAL')
 * @returns {object} Mapped BACKUP_VENDHQ_SALES row
 */
function mapSaleToVendhqSales(odooSale, options = {}) {
  const {
    region = 'AE',
    outletName = null,
    registerName = null,
    customerType = 'NORMAL'
  } = options;

  // Extract outlet/store name from Odoo warehouse or partner
  const outletNameResolved = outletName
    || (odooSale.warehouse_id ? odooSale.warehouse_id[1] : null)
    || (odooSale.partner_id ? odooSale.partner_id[1] : null)
    || 'UNKNOWN';

  // Extract register name from POS session or config
  const registerNameResolved = registerName
    || (odooSale.pos_config_id ? odooSale.pos_config_id[1] : null)
    || (odooSale.session_id ? odooSale.session_id[1] : null)
    || 'MAIN';

  // Parse amounts (Odoo returns numbers, but we ensure they're valid)
  const amountUntaxed = parseFloat(odooSale.amount_untaxed) || 0;
  const amountTax = parseFloat(odooSale.amount_tax) || 0;
  const amountTotal = parseFloat(odooSale.amount_total) || 0;
  const amountDiscount = parseFloat(odooSale.amount_discount) || 0; // If available

  // Parse sale date
  const saleDate = odooSale.date_order
    ? new Date(odooSale.date_order)
    : new Date();

  return {
    // ROW_ID will be auto-generated by database or assigned during insert
    INVOICE_NUMBER: odooSale.name || odooSale.id?.toString() || 'UNKNOWN',
    OUTLET_NAME: outletNameResolved,
    REGISTER_NAME: registerNameResolved,
    SALE_DATE: saleDate,
    TOTAL_PRICE: amountUntaxed,
    TOTAL_TAX: amountTax,
    TOTAL_LOYALTY: amountDiscount, // Discounts treated as loyalty in VendHQ model
    TOTAL_PRICE_INCL_TAX: amountTotal,
    VERSION: 0, // Always 0 for Odoo integration
    REGION: region,
    CUSTOMER_TYPE: customerType
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. Sale Order Line → BACKUP_VENDHQ_LINE_ITEMS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Map Odoo sale.order.line to BACKUP_VENDHQ_LINE_ITEMS table structure.
 *
 * BACKUP_VENDHQ_LINE_ITEMS columns:
 *   - ROW_ID: NUMBER (Primary Key, auto-generated)
 *   - INVOICE_NUMBER: VARCHAR2(300) - Links to BACKUP_VENDHQ_SALES
 *   - LINE_NUMBER: NUMBER - Line sequence number
 *   - ITEM_NUMBER: VARCHAR2(50) - Product internal reference/SKU
 *   - ITEM_NAME: VARCHAR2(250) - Product name/description
 *   - QUANTITY: NUMBER - Quantity ordered
 *   - LOYALTY_VALUE: NUMBER - Line discount amount
 *   - TOTAL_PRICE: NUMBER - Line subtotal (price * qty - discount)
 *   - TOTAL_TAX: NUMBER - Line tax amount
 *   - TOTAL_DISCOUNT: NUMBER - Line discount amount (same as LOYALTY_VALUE)
 *   - TOTAL_LOYALTY: NUMBER - Line loyalty points (if applicable)
 *   - REGION: VARCHAR2(5) - Region code (inherited from sale)
 *   - SALE_DATE: DATE - Sale date (inherited from sale)
 *   - TAX_NAME: VARCHAR2(100) - Tax classification code
 *
 * @param {object} odooLine - Odoo sale.order.line object from API
 * @param {string} invoiceNumber - Parent sale order name/reference
 * @param {object} options - Additional mapping options
 * @param {string} options.region - Region code
 * @param {Date} options.saleDate - Sale date from parent order
 * @param {number} options.lineNumber - Line sequence override
 * @returns {object} Mapped BACKUP_VENDHQ_LINE_ITEMS row
 */
function mapLineToVendhqLineItems(odooLine, invoiceNumber, options = {}) {
  const {
    region = 'AE',
    saleDate = new Date(),
    lineNumber = null
  } = options;

  // Extract product information
  const productId = Array.isArray(odooLine.product_id)
    ? odooLine.product_id[0]
    : odooLine.product_id;
  const productName = Array.isArray(odooLine.product_id)
    ? odooLine.product_id[1]
    : (odooLine.name || 'Unknown Product');

  // Product SKU/internal reference (default_code in Odoo)
  const itemNumber = odooLine.product_code
    || odooLine.default_code
    || productId?.toString()
    || 'MISC';

  // Parse line amounts
  const quantity = parseFloat(odooLine.product_uom_qty) || parseFloat(odooLine.qty) || 0;
  const priceUnit = parseFloat(odooLine.price_unit) || 0;
  const priceSubtotal = parseFloat(odooLine.price_subtotal) || 0;
  const priceTax = parseFloat(odooLine.price_tax) || 0;
  const discount = parseFloat(odooLine.discount) || 0;

  // Calculate discount amount (discount is percentage in Odoo)
  const discountAmount = (priceUnit * quantity * discount) / 100;

  // Extract tax name/code
  const taxName = odooLine.tax_id
    ? (Array.isArray(odooLine.tax_id) && odooLine.tax_id.length > 0
        ? (Array.isArray(odooLine.tax_id[0]) ? odooLine.tax_id[0][1] : 'TAX')
        : 'TAX')
    : 'NONE';

  // Line number (sequence)
  const lineNum = lineNumber !== null
    ? lineNumber
    : (odooLine.sequence || odooLine.id || 1);

  return {
    // ROW_ID will be auto-generated
    INVOICE_NUMBER: invoiceNumber,
    LINE_NUMBER: lineNum,
    ITEM_NUMBER: itemNumber,
    ITEM_NAME: productName,
    QUANTITY: quantity,
    LOYALTY_VALUE: discountAmount,
    TOTAL_PRICE: priceSubtotal,
    TOTAL_TAX: priceTax,
    TOTAL_DISCOUNT: discountAmount,
    TOTAL_LOYALTY: 0, // Loyalty points not typically tracked at line level
    REGION: region,
    SALE_DATE: saleDate,
    TAX_NAME: taxName
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. Account Payment → BACKUP_VENDHQ_PAYMENTS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Map Odoo account.payment to BACKUP_VENDHQ_PAYMENTS table structure.
 *
 * BACKUP_VENDHQ_PAYMENTS columns:
 *   - ROW_ID: NUMBER (Primary Key, auto-generated)
 *   - INVOICE_NUMBER: VARCHAR2(300) - Links to BACKUP_VENDHQ_SALES
 *   - OUTLET_NAME: VARCHAR2(100) - Store/outlet name
 *   - REGISTER_NAME: VARCHAR2(100) - Register name
 *   - AMOUNT: NUMBER - Payment amount
 *   - CURRENCY: VARCHAR2(5) - Currency code
 *   - PAYMENT_TYPE: VARCHAR2(100) - Payment method type
 *   - PAYMENT_DATE: DATE - Payment date
 *   - DELETED_AT: DATE - Soft delete timestamp (NULL if active)
 *   - REGION: VARCHAR2(5) - Region code
 *   - SALE_DATE: DATE - Original sale date
 *
 * Payment types map to Oracle operations:
 *   - Cash, Card, Bank Transfer → Standard Receipt
 *   - Cash Rounding, Tip, Service Charge → Misc Receipt
 *
 * @param {object} odooPayment - Odoo account.payment object from API
 * @param {string} invoiceNumber - Associated sale order reference
 * @param {object} options - Additional mapping options
 * @param {string} options.region - Region code
 * @param {string} options.outletName - Store/outlet name
 * @param {string} options.registerName - Register name
 * @param {Date} options.saleDate - Original sale date
 * @returns {object} Mapped BACKUP_VENDHQ_PAYMENTS row
 */
function mapPaymentToVendhqPayments(odooPayment, invoiceNumber, options = {}) {
  const {
    region = 'AE',
    outletName = 'UNKNOWN',
    registerName = 'MAIN',
    saleDate = new Date()
  } = options;

  // Parse payment amount
  const amount = parseFloat(odooPayment.amount) || 0;

  // Extract currency (fallback to AED)
  const currency = odooPayment.currency_id
    ? (Array.isArray(odooPayment.currency_id) ? odooPayment.currency_id[1] : 'AED')
    : 'AED';

  // Extract payment method/type
  // In Odoo, payment_method_id or journal_id defines the payment type
  const paymentType = odooPayment.payment_method_code
    || (odooPayment.payment_method_id && Array.isArray(odooPayment.payment_method_id)
        ? odooPayment.payment_method_id[1]
        : null)
    || (odooPayment.journal_id && Array.isArray(odooPayment.journal_id)
        ? odooPayment.journal_id[1]
        : null)
    || 'Cash';

  // Parse payment date
  const paymentDate = odooPayment.date || odooPayment.payment_date
    ? new Date(odooPayment.date || odooPayment.payment_date)
    : saleDate;

  return {
    // ROW_ID will be auto-generated
    INVOICE_NUMBER: invoiceNumber,
    OUTLET_NAME: outletName,
    REGISTER_NAME: registerName,
    AMOUNT: amount,
    CURRENCY: currency,
    PAYMENT_TYPE: paymentType,
    PAYMENT_DATE: paymentDate,
    DELETED_AT: null, // NULL = active payment
    REGION: region,
    SALE_DATE: saleDate
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. Oracle Operation Classification Helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Classify a payment as Standard Receipt or Misc Receipt based on payment type.
 *
 * Standard Receipt: Main payment methods (Cash, Card, Bank, etc.)
 * Misc Receipt: Adjustments (Rounding, Tips, Service Charges)
 *
 * @param {string} paymentType - Payment type from BACKUP_VENDHQ_PAYMENTS
 * @returns {string} 'STANDARD' or 'MISC'
 */
function classifyReceiptType(paymentType) {
  const lowerType = (paymentType || '').toLowerCase();

  // Misc receipts: rounding, tips, service charges
  if (lowerType.includes('rounding')
      || lowerType.includes('tip')
      || lowerType.includes('service')
      || lowerType.includes('adjustment')) {
    return 'MISC';
  }

  // Default: Standard receipt
  return 'STANDARD';
}

/**
 * Determine if a customer type requires a journal entry.
 *
 * Journal entries are created for service provider charges:
 *   - HUNGERSTATION, TALABAT, DELIVEROO, etc. (commission charges)
 *
 * @param {string} customerType - Customer type from BACKUP_VENDHQ_SALES
 * @returns {boolean} True if journal entry is needed
 */
function requiresJournalEntry(customerType) {
  const serviceProviders = [
    'HUNGERSTATION',
    'TALABAT',
    'DELIVEROO',
    'ZOMATO',
    'NOON',
    'CAREEM',
    'UBER'
  ];

  return serviceProviders.includes((customerType || '').toUpperCase());
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. Batch Mapping Functions
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Map a complete Odoo sale order with lines and payments to VendHQ backup structure.
 *
 * @param {object} odooSale - Odoo sale.order object
 * @param {Array} odooLines - Array of sale.order.line objects
 * @param {Array} odooPayments - Array of account.payment objects
 * @param {object} options - Mapping options (region, outlet, etc.)
 * @returns {object} Complete mapped structure with sales, lines, and payments
 */
function mapCompleteSale(odooSale, odooLines = [], odooPayments = [], options = {}) {
  const {
    region = 'AE',
    outletName = null,
    registerName = null,
    customerType = 'NORMAL'
  } = options;

  // Map sale header
  const mappedSale = mapSaleToVendhqSales(odooSale, {
    region,
    outletName,
    registerName,
    customerType
  });

  const invoiceNumber = mappedSale.INVOICE_NUMBER;
  const saleDate = mappedSale.SALE_DATE;

  // Map line items
  const mappedLines = odooLines.map((line, index) =>
    mapLineToVendhqLineItems(line, invoiceNumber, {
      region,
      saleDate,
      lineNumber: index + 1
    })
  );

  // Map payments
  const mappedPayments = odooPayments.map(payment =>
    mapPaymentToVendhqPayments(payment, invoiceNumber, {
      region,
      outletName: mappedSale.OUTLET_NAME,
      registerName: mappedSale.REGISTER_NAME,
      saleDate
    })
  );

  return {
    sale: mappedSale,
    lines: mappedLines,
    payments: mappedPayments,
    metadata: {
      invoiceNumber,
      region,
      customerType,
      requiresJournal: requiresJournalEntry(customerType),
      paymentClassifications: mappedPayments.map(p => ({
        type: p.PAYMENT_TYPE,
        classification: classifyReceiptType(p.PAYMENT_TYPE)
      }))
    }
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Exports
// ─────────────────────────────────────────────────────────────────────────────

module.exports = {
  // Individual mappers
  mapSaleToVendhqSales,
  mapLineToVendhqLineItems,
  mapPaymentToVendhqPayments,

  // Classification helpers
  classifyReceiptType,
  requiresJournalEntry,

  // Batch mapper
  mapCompleteSale
};
