
package com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ItemCatalogService", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/", wsdlLocation = "https://ehxk-test.fa.em2.oraclecloud.com/fscmService/ItemCatalogService?WSDL")
public class ItemCatalogService_Service
    extends Service
{

    private final static URL ITEMCATALOGSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMCATALOGSERVICE_EXCEPTION;
    private final static QName ITEMCATALOGSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/", "ItemCatalogService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ehxk-test.fa.em2.oraclecloud.com/fscmService/ItemCatalogService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMCATALOGSERVICE_WSDL_LOCATION = url;
        ITEMCATALOGSERVICE_EXCEPTION = e;
    }

    public ItemCatalogService_Service() {
        super(__getWsdlLocation(), ITEMCATALOGSERVICE_QNAME);
    }

    public ItemCatalogService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMCATALOGSERVICE_QNAME, features);
    }

    public ItemCatalogService_Service(URL wsdlLocation) {
        super(wsdlLocation, ITEMCATALOGSERVICE_QNAME);
    }

    public ItemCatalogService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMCATALOGSERVICE_QNAME, features);
    }

    public ItemCatalogService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemCatalogService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemCatalogService
     */
    @WebEndpoint(name = "ItemCatalogServiceSoapHttpPort")
    public ItemCatalogService getItemCatalogServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/", "ItemCatalogServiceSoapHttpPort"), ItemCatalogService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemCatalogService
     */
    @WebEndpoint(name = "ItemCatalogServiceSoapHttpPort")
    public ItemCatalogService getItemCatalogServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/", "ItemCatalogServiceSoapHttpPort"), ItemCatalogService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMCATALOGSERVICE_EXCEPTION!= null) {
            throw ITEMCATALOGSERVICE_EXCEPTION;
        }
        return ITEMCATALOGSERVICE_WSDL_LOCATION;
    }

}
