
package com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.xmlns.adf.svc.types.FindControl;
import com.oracle.xmlns.adf.svc.types.FindCriteria;
import com.oracle.xmlns.adf.svc.types.ProcessControl;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ItemCatalogService", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/")
@XmlSeeAlso({
    com.oracle.xmlns.adf.svc.errors.ObjectFactory.class,
    com.oracle.xmlns.adf.svc.types.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productmodel.catalogs.flex.catalog.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productmodel.catalogs.flex.category.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.ObjectFactory.class,
    com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class,
    sdo.commonj.ObjectFactory.class,
    sdo.commonj.java.ObjectFactory.class,
    sdo.commonj.xml.ObjectFactory.class
})
public interface ItemCatalogService {


    /**
     * 
     * @param catalog
     * @return
     *     returns com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Catalog
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/createCatalog")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "createCatalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.CreateCatalog")
    @ResponseWrapper(localName = "createCatalogResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.CreateCatalogResponse")
    public Catalog createCatalog(
        @WebParam(name = "catalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Catalog catalog)
        throws ServiceException
    ;

    /**
     * 
     * @param catalog
     * @return
     *     returns com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Catalog
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/updateCatalog")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "updateCatalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.UpdateCatalog")
    @ResponseWrapper(localName = "updateCatalogResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.UpdateCatalogResponse")
    public Catalog updateCatalog(
        @WebParam(name = "catalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Catalog catalog)
        throws ServiceException
    ;

    /**
     * 
     * @param catalog
     * @return
     *     returns com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Catalog
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/mergeCatalog")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "mergeCatalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.MergeCatalog")
    @ResponseWrapper(localName = "mergeCatalogResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.MergeCatalogResponse")
    public Catalog mergeCatalog(
        @WebParam(name = "catalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Catalog catalog)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Catalog>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/findCatalog")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "findCatalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.FindCatalog")
    @ResponseWrapper(localName = "findCatalogResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.FindCatalogResponse")
    public List<Catalog> findCatalog(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param catalog
     * @param processControl
     * @param changeOperation
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Catalog>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/processCatalog")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "processCatalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.ProcessCatalog")
    @ResponseWrapper(localName = "processCatalogResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.ProcessCatalogResponse")
    public List<Catalog> processCatalog(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String changeOperation,
        @WebParam(name = "catalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        List<Catalog> catalog,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param category
     * @return
     *     returns com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Category
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/createCategory")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "createCategory", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.CreateCategory")
    @ResponseWrapper(localName = "createCategoryResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.CreateCategoryResponse")
    public Category createCategory(
        @WebParam(name = "category", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Category category)
        throws ServiceException
    ;

    /**
     * 
     * @param category
     * @return
     *     returns com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Category
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/updateCategory")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "updateCategory", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.UpdateCategory")
    @ResponseWrapper(localName = "updateCategoryResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.UpdateCategoryResponse")
    public Category updateCategory(
        @WebParam(name = "category", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Category category)
        throws ServiceException
    ;

    /**
     * 
     * @param category
     * @return
     *     returns com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Category
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/mergeCategory")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "mergeCategory", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.MergeCategory")
    @ResponseWrapper(localName = "mergeCategoryResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.MergeCategoryResponse")
    public Category mergeCategory(
        @WebParam(name = "category", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Category category)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Category>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/findCategory")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "findCategory", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.FindCategory")
    @ResponseWrapper(localName = "findCategoryResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.FindCategoryResponse")
    public List<Category> findCategory(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param category
     * @param changeOperation
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Category>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/processCategory")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "processCategory", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.ProcessCategory")
    @ResponseWrapper(localName = "processCategoryResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.ProcessCategoryResponse")
    public List<Category> processCategory(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String changeOperation,
        @WebParam(name = "category", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        List<Category> category,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param catalog
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/mergeCatalogAsync")
    @Oneway
    @RequestWrapper(localName = "mergeCatalogAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.MergeCatalogAsync")
    public void mergeCatalogAsync(
        @WebParam(name = "catalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Catalog catalog);

    /**
     * 
     * @param catalog
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/createCatalogAsync")
    @Oneway
    @RequestWrapper(localName = "createCatalogAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.CreateCatalogAsync")
    public void createCatalogAsync(
        @WebParam(name = "catalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Catalog catalog);

    /**
     * 
     * @param processControl
     * @param category
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/processCategoryAsync")
    @Oneway
    @RequestWrapper(localName = "processCategoryAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.ProcessCategoryAsync")
    public void processCategoryAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String changeOperation,
        @WebParam(name = "category", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        List<Category> category,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param category
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/updateCategoryAsync")
    @Oneway
    @RequestWrapper(localName = "updateCategoryAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.UpdateCategoryAsync")
    public void updateCategoryAsync(
        @WebParam(name = "category", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Category category);

    /**
     * 
     * @param catalog
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/updateCatalogAsync")
    @Oneway
    @RequestWrapper(localName = "updateCatalogAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.UpdateCatalogAsync")
    public void updateCatalogAsync(
        @WebParam(name = "catalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Catalog catalog);

    /**
     * 
     * @param catalog
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/processCatalogAsync")
    @Oneway
    @RequestWrapper(localName = "processCatalogAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.ProcessCatalogAsync")
    public void processCatalogAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String changeOperation,
        @WebParam(name = "catalog", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        List<Catalog> catalog,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/findCatalogAsync")
    @Oneway
    @RequestWrapper(localName = "findCatalogAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.FindCatalogAsync")
    public void findCatalogAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindControl findControl);

    /**
     * 
     * @param category
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/createCategoryAsync")
    @Oneway
    @RequestWrapper(localName = "createCategoryAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.CreateCategoryAsync")
    public void createCategoryAsync(
        @WebParam(name = "category", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Category category);

    /**
     * 
     * @param category
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/mergeCategoryAsync")
    @Oneway
    @RequestWrapper(localName = "mergeCategoryAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.MergeCategoryAsync")
    public void mergeCategoryAsync(
        @WebParam(name = "category", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        Category category);

    /**
     * 
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/findCategoryAsync")
    @Oneway
    @RequestWrapper(localName = "findCategoryAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.FindCategoryAsync")
    public void findCategoryAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindControl findControl);

    /**
     * 
     * @param targetCategoryCode
     * @param sourceCategoryCode
     * @param targetCatalogCode
     * @param copyItemAssignmentsFlag
     * @param copyChildCategoriesFlag
     * @param sourceCatalogCode
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Category>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/copyCategory")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "copyCategory", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.CopyCategory")
    @ResponseWrapper(localName = "copyCategoryResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.CopyCategoryResponse")
    public List<Category> copyCategory(
        @WebParam(name = "sourceCatalogCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String sourceCatalogCode,
        @WebParam(name = "sourceCategoryCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String sourceCategoryCode,
        @WebParam(name = "targetCatalogCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String targetCatalogCode,
        @WebParam(name = "targetCategoryCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String targetCategoryCode,
        @WebParam(name = "CopyChildCategoriesFlag", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        boolean copyChildCategoriesFlag,
        @WebParam(name = "CopyItemAssignmentsFlag", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        boolean copyItemAssignmentsFlag)
        throws ServiceException
    ;

    /**
     * 
     * @param targetCategoryCode
     * @param sourceCategoryCode
     * @param targetCatalogCode
     * @param sourceCatalogCode
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/addSharedCategories")
    @RequestWrapper(localName = "addSharedCategories", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.AddSharedCategories")
    @ResponseWrapper(localName = "addSharedCategoriesResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.AddSharedCategoriesResponse")
    public void addSharedCategories(
        @WebParam(name = "sourceCatalogCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String sourceCatalogCode,
        @WebParam(name = "sourceCategoryCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String sourceCategoryCode,
        @WebParam(name = "targetCatalogCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String targetCatalogCode,
        @WebParam(name = "targetCategoryCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String targetCategoryCode)
        throws ServiceException
    ;

    /**
     * 
     * @param targetCategoryCode
     * @param sourceCategoryCode
     * @param targetCatalogCode
     * @param sourceCatalogCode
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/addSharedCategoriesAsync")
    @Oneway
    @RequestWrapper(localName = "addSharedCategoriesAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.AddSharedCategoriesAsync")
    public void addSharedCategoriesAsync(
        @WebParam(name = "sourceCatalogCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String sourceCatalogCode,
        @WebParam(name = "sourceCategoryCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String sourceCategoryCode,
        @WebParam(name = "targetCatalogCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String targetCatalogCode,
        @WebParam(name = "targetCategoryCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String targetCategoryCode);

    /**
     * 
     * @param targetCategoryCode
     * @param sourceCategoryCode
     * @param targetCatalogCode
     * @param copyItemAssignmentsFlag
     * @param copyChildCategoriesFlag
     * @param sourceCatalogCode
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/copyCategoryAsync")
    @Oneway
    @RequestWrapper(localName = "copyCategoryAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.CopyCategoryAsync")
    public void copyCategoryAsync(
        @WebParam(name = "sourceCatalogCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String sourceCatalogCode,
        @WebParam(name = "sourceCategoryCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String sourceCategoryCode,
        @WebParam(name = "targetCatalogCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String targetCatalogCode,
        @WebParam(name = "targetCategoryCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String targetCategoryCode,
        @WebParam(name = "CopyChildCategoriesFlag", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        boolean copyChildCategoriesFlag,
        @WebParam(name = "CopyItemAssignmentsFlag", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        boolean copyItemAssignmentsFlag);

    /**
     * 
     * @param catalogName
     * @param catalogId
     * @param catalogCode
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.Category>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/getCatalogCategories")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "getCatalogCategories", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.GetCatalogCategories")
    @ResponseWrapper(localName = "getCatalogCategoriesResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.GetCatalogCategoriesResponse")
    public List<Category> getCatalogCategories(
        @WebParam(name = "catalogId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        long catalogId,
        @WebParam(name = "catalogCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String catalogCode,
        @WebParam(name = "catalogName", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String catalogName)
        throws ServiceException
    ;

    /**
     * 
     * @param catalogName
     * @param catalogId
     * @param catalogCode
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/getCatalogCategoriesAsync")
    @Oneway
    @RequestWrapper(localName = "getCatalogCategoriesAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.GetCatalogCategoriesAsync")
    public void getCatalogCategoriesAsync(
        @WebParam(name = "catalogId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        long catalogId,
        @WebParam(name = "catalogCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String catalogCode,
        @WebParam(name = "catalogName", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        String catalogName);

    /**
     * 
     * @param catalogId
     * @return
     *     returns com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.CatalogReadOnly
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/getCatalogHierarchy")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "getCatalogHierarchy", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.GetCatalogHierarchy")
    @ResponseWrapper(localName = "getCatalogHierarchyResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.GetCatalogHierarchyResponse")
    public CatalogReadOnly getCatalogHierarchy(
        @WebParam(name = "catalogId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        long catalogId)
        throws ServiceException
    ;

    /**
     * 
     * @param catalogId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/getCatalogHierarchyAsync")
    @Oneway
    @RequestWrapper(localName = "getCatalogHierarchyAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.GetCatalogHierarchyAsync")
    public void getCatalogHierarchyAsync(
        @WebParam(name = "catalogId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        long catalogId);

    /**
     * 
     * @param findCriteria
     * @param findControl
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.CatalogReadOnly>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/findCatalogHierarchy")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
    @RequestWrapper(localName = "findCatalogHierarchy", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.FindCatalogHierarchy")
    @ResponseWrapper(localName = "findCatalogHierarchyResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.FindCatalogHierarchyResponse")
    public List<CatalogReadOnly> findCatalogHierarchy(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/findCatalogHierarchyAsync")
    @Oneway
    @RequestWrapper(localName = "findCatalogHierarchyAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/", className = "com.oracle.xmlns.apps.scm.productmodel.catalogs.itemcatalogservice.types.FindCatalogHierarchyAsync")
    public void findCatalogHierarchyAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/catalogs/itemCatalogService/types/")
        FindControl findControl);

}
