
package com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2;

import innovate.tamergroup.shared.utils.FusionAppParams;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExternalBankAccountService", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/", wsdlLocation = "https://ehxk-test.fa.em2.oraclecloud.com/fscmService/ExternalBankAccountServiceV2?WSDL")
public class ExternalBankAccountService_Service
    extends Service
{

    private final static URL EXTERNALBANKACCOUNTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXTERNALBANKACCOUNTSERVICE_EXCEPTION;
    private final static QName EXTERNALBANKACCOUNTSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/", "ExternalBankAccountService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ehxk-test.fa.em2.oraclecloud.com/fscmService/ExternalBankAccountServiceV2?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXTERNALBANKACCOUNTSERVICE_WSDL_LOCATION = url;
        EXTERNALBANKACCOUNTSERVICE_EXCEPTION = e;
    }

    public ExternalBankAccountService_Service() {
        super(__getWsdlLocation(), EXTERNALBANKACCOUNTSERVICE_QNAME);
    }

    public ExternalBankAccountService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXTERNALBANKACCOUNTSERVICE_QNAME, features);
    }

    public ExternalBankAccountService_Service(URL wsdlLocation) {
        super(wsdlLocation, EXTERNALBANKACCOUNTSERVICE_QNAME);
    }
    
    public ExternalBankAccountService_Service(FusionAppParams params) throws MalformedURLException {
        super(new URL("https://" + params.getHostname() + ".fa." + params.getRegion() + ".oraclecloud.com/fscmService/ExternalBankAccountServiceV2?WSDL"), EXTERNALBANKACCOUNTSERVICE_QNAME);
    }

    public ExternalBankAccountService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXTERNALBANKACCOUNTSERVICE_QNAME, features);
    }

    public ExternalBankAccountService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExternalBankAccountService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExternalBankAccountService
     */
    @WebEndpoint(name = "ExternalBankAccountServiceSoapHttpPort")
    public ExternalBankAccountService getExternalBankAccountServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/", "ExternalBankAccountServiceSoapHttpPort"), ExternalBankAccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExternalBankAccountService
     */
    @WebEndpoint(name = "ExternalBankAccountServiceSoapHttpPort")
    public ExternalBankAccountService getExternalBankAccountServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/", "ExternalBankAccountServiceSoapHttpPort"), ExternalBankAccountService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXTERNALBANKACCOUNTSERVICE_EXCEPTION!= null) {
            throw EXTERNALBANKACCOUNTSERVICE_EXCEPTION;
        }
        return EXTERNALBANKACCOUNTSERVICE_WSDL_LOCATION;
    }

}
