
package com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.xmlns.adf.svc.types.FindControl;
import com.oracle.xmlns.adf.svc.types.FindCriteria;
import com.oracle.xmlns.adf.svc.types.ObjAttrHints;
import com.oracle.xmlns.adf.svc.types.ServiceViewInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExternalBankAccountService", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/")
@XmlSeeAlso({
    com.oracle.xmlns.adf.svc.errors.ObjectFactory.class,
    com.oracle.xmlns.adf.svc.types.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.ObjectFactory.class,
    com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.flex.bankaccountdff.ObjectFactory.class,
    com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class,
    sdo.commonj.ObjectFactory.class,
    sdo.commonj.java.ObjectFactory.class,
    sdo.commonj.xml.ObjectFactory.class
})
public interface ExternalBankAccountService {


    /**
     * 
     * @param externalBankAccountId
     * @return
     *     returns com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.ExternalBankAccount
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getExternalBankAccountDetails")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
    @RequestWrapper(localName = "getExternalBankAccountDetails", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetExternalBankAccountDetails")
    @ResponseWrapper(localName = "getExternalBankAccountDetailsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetExternalBankAccountDetailsResponse")
    public ExternalBankAccount getExternalBankAccountDetails(
        @WebParam(name = "externalBankAccountId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        long externalBankAccountId)
        throws ServiceException
    ;

    /**
     * 
     * @param accountOwnerId
     * @return
     *     returns com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.ExternalBankAccountOwner
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getExternalBankAccountOwnerRemote")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
    @RequestWrapper(localName = "getExternalBankAccountOwnerRemote", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetExternalBankAccountOwnerRemote")
    @ResponseWrapper(localName = "getExternalBankAccountOwnerRemoteResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetExternalBankAccountOwnerRemoteResponse")
    public ExternalBankAccountOwner getExternalBankAccountOwnerRemote(
        @WebParam(name = "accountOwnerId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        long accountOwnerId)
        throws ServiceException
    ;

    /**
     * 
     * @param intermediaryAccountId
     * @return
     *     returns com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.IntermediaryBankAccount
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getIntermediaryBankAccountRemote")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
    @RequestWrapper(localName = "getIntermediaryBankAccountRemote", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetIntermediaryBankAccountRemote")
    @ResponseWrapper(localName = "getIntermediaryBankAccountRemoteResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetIntermediaryBankAccountRemoteResponse")
    public IntermediaryBankAccount getIntermediaryBankAccountRemote(
        @WebParam(name = "intermediaryAccountId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        long intermediaryAccountId)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.ExternalBankAccountOwner>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/findExternalBankAccountOwnerRemote")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
    @RequestWrapper(localName = "findExternalBankAccountOwnerRemote", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.FindExternalBankAccountOwnerRemote")
    @ResponseWrapper(localName = "findExternalBankAccountOwnerRemoteResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.FindExternalBankAccountOwnerRemoteResponse")
    public List<ExternalBankAccountOwner> findExternalBankAccountOwnerRemote(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.IntermediaryBankAccount>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/findIntermediaryBankAccountRemote")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
    @RequestWrapper(localName = "findIntermediaryBankAccountRemote", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.FindIntermediaryBankAccountRemote")
    @ResponseWrapper(localName = "findIntermediaryBankAccountRemoteResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.FindIntermediaryBankAccountRemoteResponse")
    public List<IntermediaryBankAccount> findIntermediaryBankAccountRemote(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param externalBankAccountId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getExternalBankAccountDetailsAsync")
    @Oneway
    @RequestWrapper(localName = "getExternalBankAccountDetailsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetExternalBankAccountDetailsAsync")
    public void getExternalBankAccountDetailsAsync(
        @WebParam(name = "externalBankAccountId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        long externalBankAccountId);

    /**
     * 
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/findExternalBankAccountOwnerRemoteAsync")
    @Oneway
    @RequestWrapper(localName = "findExternalBankAccountOwnerRemoteAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.FindExternalBankAccountOwnerRemoteAsync")
    public void findExternalBankAccountOwnerRemoteAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindControl findControl);

    /**
     * 
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/findIntermediaryBankAccountRemoteAsync")
    @Oneway
    @RequestWrapper(localName = "findIntermediaryBankAccountRemoteAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.FindIntermediaryBankAccountRemoteAsync")
    public void findIntermediaryBankAccountRemoteAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindControl findControl);

    /**
     * 
     * @param accountOwnerId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getExternalBankAccountOwnerRemoteAsync")
    @Oneway
    @RequestWrapper(localName = "getExternalBankAccountOwnerRemoteAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetExternalBankAccountOwnerRemoteAsync")
    public void getExternalBankAccountOwnerRemoteAsync(
        @WebParam(name = "accountOwnerId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        long accountOwnerId);

    /**
     * 
     * @param intermediaryAccountId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getIntermediaryBankAccountRemoteAsync")
    @Oneway
    @RequestWrapper(localName = "getIntermediaryBankAccountRemoteAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetIntermediaryBankAccountRemoteAsync")
    public void getIntermediaryBankAccountRemoteAsync(
        @WebParam(name = "intermediaryAccountId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        long intermediaryAccountId);

    /**
     * 
     * @param branchId
     * @param bankId
     * @param accountName
     * @param countryCode
     * @param bankAccountNumber
     * @param currency
     * @return
     *     returns long
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/confirmBankAccountExistence")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
    @RequestWrapper(localName = "confirmBankAccountExistence", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.ConfirmBankAccountExistence")
    @ResponseWrapper(localName = "confirmBankAccountExistenceResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.ConfirmBankAccountExistenceResponse")
    public long confirmBankAccountExistence(
        @WebParam(name = "bankId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String bankId,
        @WebParam(name = "branchId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        BigDecimal branchId,
        @WebParam(name = "bankAccountNumber", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String bankAccountNumber,
        @WebParam(name = "accountName", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String accountName,
        @WebParam(name = "currency", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String currency,
        @WebParam(name = "countryCode", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String countryCode)
        throws ServiceException
    ;

    /**
     * 
     * @param branchId
     * @param bankId
     * @param accountName
     * @param countryCode
     * @param bankAccountNumber
     * @param currency
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/confirmBankAccountExistenceAsync")
    @Oneway
    @RequestWrapper(localName = "confirmBankAccountExistenceAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.ConfirmBankAccountExistenceAsync")
    public void confirmBankAccountExistenceAsync(
        @WebParam(name = "bankId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String bankId,
        @WebParam(name = "branchId", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        BigDecimal branchId,
        @WebParam(name = "bankAccountNumber", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String bankAccountNumber,
        @WebParam(name = "accountName", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String accountName,
        @WebParam(name = "currency", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String currency,
        @WebParam(name = "countryCode", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String countryCode);

    /**
     * 
     * @param externalBankAccount
     * @return
     *     returns com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.ExternalBankAccount
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/processExternalBankAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
    @RequestWrapper(localName = "processExternalBankAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.ProcessExternalBankAccount")
    @ResponseWrapper(localName = "processExternalBankAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.ProcessExternalBankAccountResponse")
    public ExternalBankAccount processExternalBankAccount(
        @WebParam(name = "externalBankAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        ExternalBankAccount externalBankAccount)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     * @return
     *     returns java.util.List<com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.ExternalBankAccount>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/findExternalBankAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
    @RequestWrapper(localName = "findExternalBankAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.FindExternalBankAccount")
    @ResponseWrapper(localName = "findExternalBankAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.FindExternalBankAccountResponse")
    public List<ExternalBankAccount> findExternalBankAccount(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param externalBankAccount
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/processExternalBankAccountAsync")
    @Oneway
    @RequestWrapper(localName = "processExternalBankAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.ProcessExternalBankAccountAsync")
    public void processExternalBankAccountAsync(
        @WebParam(name = "externalBankAccount", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        ExternalBankAccount externalBankAccount);

    /**
     * 
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/findExternalBankAccountAsync")
    @Oneway
    @RequestWrapper(localName = "findExternalBankAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.FindExternalBankAccountAsync")
    public void findExternalBankAccountAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        FindControl findControl);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.oracle.xmlns.adf.svc.types.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/payments/shared/bankAccounts/bankAccountServiceV2/types/", className = "com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.types.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

}
