
package com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2;

import com.oracle.xmlns.apps.financials.payments.shared.bankaccounts.bankaccountservicev2.ExternalBankAccountService_Service;

import innovate.tamergroup.shared.utils.FusionAppParams;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ItemService", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/", wsdlLocation = "https://ehxk-test.fa.em2.oraclecloud.com:443/fscmService/ItemServiceV2?WSDL")
public class ItemService_Service
    extends Service
{

    private final static URL ITEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMSERVICE_EXCEPTION;
    private final static QName ITEMSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/", "ItemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ehxk-test.fa.em2.oraclecloud.com:443/fscmService/ItemServiceV2?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMSERVICE_WSDL_LOCATION = url;
        ITEMSERVICE_EXCEPTION = e;
    }

    public ItemService_Service() {
        super(__getWsdlLocation(), ITEMSERVICE_QNAME);
    }

    public ItemService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMSERVICE_QNAME, features);
    }

    public ItemService_Service(URL wsdlLocation) {
        super(wsdlLocation, ITEMSERVICE_QNAME);
    }
    
    public ItemService_Service(FusionAppParams params) throws MalformedURLException {
        super(new URL("https://" + params.getHostname() + ".fa." + params.getRegion() + ".oraclecloud.com:443/fscmService/ItemServiceV2?WSDL"), ITEMSERVICE_QNAME);
    }

    public ItemService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMSERVICE_QNAME, features);
    }

    public ItemService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemService
     */
    @WebEndpoint(name = "ItemServiceSoapHttpPort")
    public ItemService getItemServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/", "ItemServiceSoapHttpPort"), ItemService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemService
     */
    @WebEndpoint(name = "ItemServiceSoapHttpPort")
    public ItemService getItemServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/", "ItemServiceSoapHttpPort"), ItemService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMSERVICE_EXCEPTION!= null) {
            throw ITEMSERVICE_EXCEPTION;
        }
        return ITEMSERVICE_WSDL_LOCATION;
    }

}
