
package com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.xmlns.adf.svc.types.DataObjectResult;
import com.oracle.xmlns.adf.svc.types.FindControl;
import com.oracle.xmlns.adf.svc.types.FindCriteria;
import com.oracle.xmlns.adf.svc.types.ProcessControl;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ItemService", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/")
@XmlSeeAlso({
    com.oracle.xmlns.adf.svc.errors.ObjectFactory.class,
    com.oracle.xmlns.adf.svc.types.ObjectFactory.class,
    com.oracle.xmlns.apps.flex.fnd.applcore.attachments.model.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productcatalogmanagement.advanceditems.flex.egoitemeff.item.categories.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productcatalogmanagement.advanceditems.flex.egoitemeff.itemrevision.categories.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productcatalogmanagement.advanceditems.flex.egoitemeff.itemsupplier.categories.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productmodel.items.flex.item.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productmodel.items.flex.itemgdf.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productmodel.items.flex.itemrevision.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.ObjectFactory.class,
    com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.ObjectFactory.class,
    com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class,
    sdo.commonj.ObjectFactory.class,
    sdo.commonj.java.ObjectFactory.class,
    sdo.commonj.xml.ObjectFactory.class
})
public interface ItemService {


    /**
     * 
     * @param itemId
     * @param itemNumber
     * @param deleteGroupName
     * @param orgId
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteItem")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "deleteItem", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItem")
    @ResponseWrapper(localName = "deleteItemResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItemResponse")
    public String deleteItem(
        @WebParam(name = "itemId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long itemId,
        @WebParam(name = "orgId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long orgId,
        @WebParam(name = "itemNumber", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemNumber,
        @WebParam(name = "deleteGroupName", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String deleteGroupName)
        throws ServiceException
    ;

    /**
     * 
     * @param itemId
     * @param itemNumber
     * @param deleteGroupName
     * @param orgId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteItemAsync")
    @Oneway
    @RequestWrapper(localName = "deleteItemAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItemAsync")
    public void deleteItemAsync(
        @WebParam(name = "itemId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long itemId,
        @WebParam(name = "orgId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long orgId,
        @WebParam(name = "itemNumber", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemNumber,
        @WebParam(name = "deleteGroupName", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String deleteGroupName);

    /**
     * 
     * @param itemNumber
     * @param organizationCode
     * @param effectiveDateTime
     * @param itemRevision
     * @param version
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/getItemVersions")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "getItemVersions", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.GetItemVersions")
    @ResponseWrapper(localName = "getItemVersionsResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.GetItemVersionsResponse")
    public DataObjectResult getItemVersions(
        @WebParam(name = "itemNumber", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemNumber,
        @WebParam(name = "organizationCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String organizationCode,
        @WebParam(name = "itemRevision", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemRevision,
        @WebParam(name = "version", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String version,
        @WebParam(name = "effectiveDateTime", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        XMLGregorianCalendar effectiveDateTime)
        throws ServiceException
    ;

    /**
     * 
     * @param versionDescription
     * @param itemNumber
     * @param versionId
     * @param versionLabel
     * @param organizationCode
     * @param newRevision
     * @param itemRevision
     * @param plannedEffectiveDateAndTime
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/releaseVersionItem")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "releaseVersionItem", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.ReleaseVersionItem")
    @ResponseWrapper(localName = "releaseVersionItemResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.ReleaseVersionItemResponse")
    public DataObjectResult releaseVersionItem(
        @WebParam(name = "versionId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        Long versionId,
        @WebParam(name = "itemNumber", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemNumber,
        @WebParam(name = "organizationCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String organizationCode,
        @WebParam(name = "itemRevision", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemRevision,
        @WebParam(name = "newRevision", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String newRevision,
        @WebParam(name = "versionLabel", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String versionLabel,
        @WebParam(name = "versionDescription", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String versionDescription,
        @WebParam(name = "plannedEffectiveDateAndTime", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        XMLGregorianCalendar plannedEffectiveDateAndTime)
        throws ServiceException
    ;

    /**
     * 
     * @param itemNumber
     * @param versionId
     * @param organizationCode
     * @param itemRevision
     * @param version
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/cancelVersionItem")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "cancelVersionItem", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.CancelVersionItem")
    @ResponseWrapper(localName = "cancelVersionItemResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.CancelVersionItemResponse")
    public DataObjectResult cancelVersionItem(
        @WebParam(name = "versionId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        Long versionId,
        @WebParam(name = "itemNumber", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemNumber,
        @WebParam(name = "organizationCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String organizationCode,
        @WebParam(name = "itemRevision", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemRevision,
        @WebParam(name = "version", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String version)
        throws ServiceException
    ;

    /**
     * 
     * @param versionDescription
     * @param itemNumber
     * @param versionId
     * @param versionLabel
     * @param organizationCode
     * @param newRevision
     * @param itemRevision
     * @param plannedEffectiveDateAndTime
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/releaseVersionItemAsync")
    @Oneway
    @RequestWrapper(localName = "releaseVersionItemAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.ReleaseVersionItemAsync")
    public void releaseVersionItemAsync(
        @WebParam(name = "versionId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        Long versionId,
        @WebParam(name = "itemNumber", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemNumber,
        @WebParam(name = "organizationCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String organizationCode,
        @WebParam(name = "itemRevision", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemRevision,
        @WebParam(name = "newRevision", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String newRevision,
        @WebParam(name = "versionLabel", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String versionLabel,
        @WebParam(name = "versionDescription", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String versionDescription,
        @WebParam(name = "plannedEffectiveDateAndTime", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        XMLGregorianCalendar plannedEffectiveDateAndTime);

    /**
     * 
     * @param itemNumber
     * @param versionId
     * @param organizationCode
     * @param itemRevision
     * @param version
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/cancelVersionItemAsync")
    @Oneway
    @RequestWrapper(localName = "cancelVersionItemAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.CancelVersionItemAsync")
    public void cancelVersionItemAsync(
        @WebParam(name = "versionId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        Long versionId,
        @WebParam(name = "itemNumber", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemNumber,
        @WebParam(name = "organizationCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String organizationCode,
        @WebParam(name = "itemRevision", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemRevision,
        @WebParam(name = "version", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String version);

    /**
     * 
     * @param itemNumber
     * @param organizationCode
     * @param effectiveDateTime
     * @param itemRevision
     * @param version
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/getItemVersionsAsync")
    @Oneway
    @RequestWrapper(localName = "getItemVersionsAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.GetItemVersionsAsync")
    public void getItemVersionsAsync(
        @WebParam(name = "itemNumber", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemNumber,
        @WebParam(name = "organizationCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String organizationCode,
        @WebParam(name = "itemRevision", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemRevision,
        @WebParam(name = "version", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String version,
        @WebParam(name = "effectiveDateTime", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        XMLGregorianCalendar effectiveDateTime);

    /**
     * 
     * @param item
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/createItem")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "createItem", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.CreateItem")
    @ResponseWrapper(localName = "createItemResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.CreateItemResponse")
    public DataObjectResult createItem(
        @WebParam(name = "item", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        Item item)
        throws ServiceException
    ;

    /**
     * 
     * @param item
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/updateItem")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "updateItem", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.UpdateItem")
    @ResponseWrapper(localName = "updateItemResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.UpdateItemResponse")
    public DataObjectResult updateItem(
        @WebParam(name = "item", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        Item item)
        throws ServiceException
    ;

    /**
     * 
     * @param item
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/mergeItem")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "mergeItem", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.MergeItem")
    @ResponseWrapper(localName = "mergeItemResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.MergeItemResponse")
    public DataObjectResult mergeItem(
        @WebParam(name = "item", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        Item item)
        throws ServiceException
    ;

    /**
     * 
     * @param findCriteria
     * @param findControl
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/findItem")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "findItem", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.FindItem")
    @ResponseWrapper(localName = "findItemResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.FindItemResponse")
    public List<Item> findItem(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param item
     * @param processControl
     * @param changeOperation
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/processItem")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "processItem", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.ProcessItem")
    @ResponseWrapper(localName = "processItemResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.ProcessItemResponse")
    public DataObjectResult processItem(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String changeOperation,
        @WebParam(name = "item", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        List<Item> item,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param item
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/mergeItemAsync")
    @Oneway
    @RequestWrapper(localName = "mergeItemAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.MergeItemAsync")
    public void mergeItemAsync(
        @WebParam(name = "item", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        Item item);

    /**
     * 
     * @param item
     * @param processControl
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/processItemAsync")
    @Oneway
    @RequestWrapper(localName = "processItemAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.ProcessItemAsync")
    public void processItemAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String changeOperation,
        @WebParam(name = "item", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        List<Item> item,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        ProcessControl processControl);

    /**
     * 
     * @param item
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/updateItemAsync")
    @Oneway
    @RequestWrapper(localName = "updateItemAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.UpdateItemAsync")
    public void updateItemAsync(
        @WebParam(name = "item", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        Item item);

    /**
     * 
     * @param item
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/createItemAsync")
    @Oneway
    @RequestWrapper(localName = "createItemAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.CreateItemAsync")
    public void createItemAsync(
        @WebParam(name = "item", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        Item item);

    /**
     * 
     * @param findCriteria
     * @param findControl
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/findItemAsync")
    @Oneway
    @RequestWrapper(localName = "findItemAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.FindItemAsync")
    public void findItemAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        FindControl findControl);

    /**
     * 
     * @param itemCategoryAssignmentId
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteItemCategoryAssociation")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "deleteItemCategoryAssociation", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItemCategoryAssociation")
    @ResponseWrapper(localName = "deleteItemCategoryAssociationResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItemCategoryAssociationResponse")
    public String deleteItemCategoryAssociation(
        @WebParam(name = "itemCategoryAssignmentId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long itemCategoryAssignmentId)
        throws ServiceException
    ;

    /**
     * 
     * @param itemCategoryAssignmentId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteItemCategoryAssociationAsync")
    @Oneway
    @RequestWrapper(localName = "deleteItemCategoryAssociationAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItemCategoryAssociationAsync")
    public void deleteItemCategoryAssociationAsync(
        @WebParam(name = "itemCategoryAssignmentId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long itemCategoryAssignmentId);

    /**
     * 
     * @param deleteGroupName
     * @param associationId
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteSupplierSiteAssociation")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "deleteSupplierSiteAssociation", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteSupplierSiteAssociation")
    @ResponseWrapper(localName = "deleteSupplierSiteAssociationResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteSupplierSiteAssociationResponse")
    public String deleteSupplierSiteAssociation(
        @WebParam(name = "associationId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long associationId,
        @WebParam(name = "deleteGroupName", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String deleteGroupName)
        throws ServiceException
    ;

    /**
     * 
     * @param deleteGroupName
     * @param associationId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteSupplierSiteAssociationAsync")
    @Oneway
    @RequestWrapper(localName = "deleteSupplierSiteAssociationAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteSupplierSiteAssociationAsync")
    public void deleteSupplierSiteAssociationAsync(
        @WebParam(name = "associationId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long associationId,
        @WebParam(name = "deleteGroupName", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String deleteGroupName);

    /**
     * 
     * @param organizationId
     * @param sourceSystemId
     * @param sourceSystem
     * @param crossReference
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/getItemForSpokeSystemCrossReference")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "getItemForSpokeSystemCrossReference", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.GetItemForSpokeSystemCrossReference")
    @ResponseWrapper(localName = "getItemForSpokeSystemCrossReferenceResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.GetItemForSpokeSystemCrossReferenceResponse")
    public DataObjectResult getItemForSpokeSystemCrossReference(
        @WebParam(name = "sourceSystemId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long sourceSystemId,
        @WebParam(name = "sourceSystem", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String sourceSystem,
        @WebParam(name = "crossReference", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String crossReference,
        @WebParam(name = "organizationId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long organizationId)
        throws ServiceException
    ;

    /**
     * 
     * @param organizationId
     * @param sourceSystemId
     * @param sourceSystem
     * @param crossReference
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/getItemForSpokeSystemCrossReferenceAsync")
    @Oneway
    @RequestWrapper(localName = "getItemForSpokeSystemCrossReferenceAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.GetItemForSpokeSystemCrossReferenceAsync")
    public void getItemForSpokeSystemCrossReferenceAsync(
        @WebParam(name = "sourceSystemId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long sourceSystemId,
        @WebParam(name = "sourceSystem", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String sourceSystem,
        @WebParam(name = "crossReference", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String crossReference,
        @WebParam(name = "organizationId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long organizationId);

    /**
     * 
     * @param contextCode
     * @param extensibleFlexFieldLineId
     * @param associationId
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteSupplierSiteAssociationMultiRowExtensibleFlexfields")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "deleteSupplierSiteAssociationMultiRowExtensibleFlexfields", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteSupplierSiteAssociationMultiRowExtensibleFlexfields")
    @ResponseWrapper(localName = "deleteSupplierSiteAssociationMultiRowExtensibleFlexfieldsResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteSupplierSiteAssociationMultiRowExtensibleFlexfieldsResponse")
    public String deleteSupplierSiteAssociationMultiRowExtensibleFlexfields(
        @WebParam(name = "associationId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long associationId,
        @WebParam(name = "extensibleFlexFieldLineId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long extensibleFlexFieldLineId,
        @WebParam(name = "contextCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String contextCode)
        throws ServiceException
    ;

    /**
     * 
     * @param contextCode
     * @param extensibleFlexFieldLineId
     * @param associationId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteSupplierSiteAssociationMultiRowExtensibleFlexfieldsAsync")
    @Oneway
    @RequestWrapper(localName = "deleteSupplierSiteAssociationMultiRowExtensibleFlexfieldsAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteSupplierSiteAssociationMultiRowExtensibleFlexfieldsAsync")
    public void deleteSupplierSiteAssociationMultiRowExtensibleFlexfieldsAsync(
        @WebParam(name = "associationId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long associationId,
        @WebParam(name = "extensibleFlexFieldLineId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long extensibleFlexFieldLineId,
        @WebParam(name = "contextCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String contextCode);

    /**
     * 
     * @param itemId
     * @param contextCode
     * @param orgId
     * @param extensibleFlexFieldLineId
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteItemMultiRowExtensibleFlexfields")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "deleteItemMultiRowExtensibleFlexfields", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItemMultiRowExtensibleFlexfields")
    @ResponseWrapper(localName = "deleteItemMultiRowExtensibleFlexfieldsResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItemMultiRowExtensibleFlexfieldsResponse")
    public String deleteItemMultiRowExtensibleFlexfields(
        @WebParam(name = "itemId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long itemId,
        @WebParam(name = "orgId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long orgId,
        @WebParam(name = "extensibleFlexFieldLineId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long extensibleFlexFieldLineId,
        @WebParam(name = "contextCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String contextCode)
        throws ServiceException
    ;

    /**
     * 
     * @param itemId
     * @param itemRevision
     * @param contextCode
     * @param orgId
     * @param extensibleFlexFieldLineId
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteItemRevisionMultiRowExtensibleFlexfields")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
    @RequestWrapper(localName = "deleteItemRevisionMultiRowExtensibleFlexfields", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItemRevisionMultiRowExtensibleFlexfields")
    @ResponseWrapper(localName = "deleteItemRevisionMultiRowExtensibleFlexfieldsResponse", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItemRevisionMultiRowExtensibleFlexfieldsResponse")
    public String deleteItemRevisionMultiRowExtensibleFlexfields(
        @WebParam(name = "itemId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long itemId,
        @WebParam(name = "orgId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long orgId,
        @WebParam(name = "itemRevision", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemRevision,
        @WebParam(name = "extensibleFlexFieldLineId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long extensibleFlexFieldLineId,
        @WebParam(name = "contextCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String contextCode)
        throws ServiceException
    ;

    /**
     * 
     * @param itemId
     * @param itemRevision
     * @param contextCode
     * @param orgId
     * @param extensibleFlexFieldLineId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteItemRevisionMultiRowExtensibleFlexfieldsAsync")
    @Oneway
    @RequestWrapper(localName = "deleteItemRevisionMultiRowExtensibleFlexfieldsAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItemRevisionMultiRowExtensibleFlexfieldsAsync")
    public void deleteItemRevisionMultiRowExtensibleFlexfieldsAsync(
        @WebParam(name = "itemId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long itemId,
        @WebParam(name = "orgId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long orgId,
        @WebParam(name = "itemRevision", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String itemRevision,
        @WebParam(name = "extensibleFlexFieldLineId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long extensibleFlexFieldLineId,
        @WebParam(name = "contextCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String contextCode);

    /**
     * 
     * @param itemId
     * @param contextCode
     * @param orgId
     * @param extensibleFlexFieldLineId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/deleteItemMultiRowExtensibleFlexfieldsAsync")
    @Oneway
    @RequestWrapper(localName = "deleteItemMultiRowExtensibleFlexfieldsAsync", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/", className = "com.oracle.xmlns.apps.scm.productmodel.items.itemservicev2.types.DeleteItemMultiRowExtensibleFlexfieldsAsync")
    public void deleteItemMultiRowExtensibleFlexfieldsAsync(
        @WebParam(name = "itemId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long itemId,
        @WebParam(name = "orgId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long orgId,
        @WebParam(name = "extensibleFlexFieldLineId", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        long extensibleFlexFieldLineId,
        @WebParam(name = "contextCode", targetNamespace = "http://xmlns.oracle.com/apps/scm/productModel/items/itemServiceV2/types/")
        String contextCode);

}
